main/default/objects/Connected_Org__c/Connected_Org__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Connected Org</label>
</CustomObject>

main/default/objects/Connected_Org__c/fields/Data_Direction__c.field-meta.xml
<CustomField>
    <fullName>Data_Direction__c</fullName>
    <label>Data Direction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Inbound_Email__c/Inbound_Email__c.object-meta.xml
<CustomObject>
    <label>Inbound Email</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Inbound_Email__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Inbound_Email__c/fields/Html_Body__c.field-meta.xml
<CustomField>
    <fullName>Html_Body__c</fullName>
    <label>Html Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Inbound_Email__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Inbound Emails</relationshipLabel>
    <relationshipName>Inbound_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Inbound_Email__c/fields/Pharos_Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Pharos_Org_ID__c</fullName>
    <label>Pharos Org ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Id__c</fullName>
    <label>Organization Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Post_Processing_Complete__c.field-meta.xml
<CustomField>
    <fullName>Post_Processing_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Post Processing Complete</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <label>Error</label>
</RecordType>

main/default/classes/LogRestServiceTest.cls
@IsTest
private class LogRestServiceTest {

    private static final String REST_URI = '/services/apexrest/'+ ConfigUtil.nameSpacePrefix +'/logs/';

    @TestSetup
    private static void testSetup() {
        TestDataFactory.createConnectedOrg();
    }

    @IsTest
    static void test_retrieve_logs_success() {
        Log__c log = new Log__c();
        insert log;

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = REST_URI;
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        LogRestService.doGet();
        Test.stopTest();

        String jsonResponse = res.responseBody.toString();
        System.assertNotEquals(null, jsonResponse);
        Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);

        System.assertEquals(LogRestService.STATUS_SUCCESS, (String)result.get('status'));
        System.assertEquals(null, result.get('error'));
        System.assertNotEquals(null, (List<Object>)result.get('logs'));
        System.assertNotEquals(0, ((List<Object>)result.get('logs')).size());
    }

    @IsTest
    static void test_retrieve_logs_fail() {
        Log__c log = new Log__c();
        insert log;

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = REST_URI;
        req.addParameter('startDate', 'wrong date');
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        LogRestService.doGet();
        Test.stopTest();

        String jsonResponse = res.responseBody.toString();
        System.assertNotEquals(null, jsonResponse);

        Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);
        System.assertEquals(LogRestService.STATUS_FAIL, (String)result.get('status'));
        System.assertNotEquals(null, result.get('error'));
        System.assertEquals(null, (List<Object>)result.get('logs'));
    }

    @IsTest
    static void test_retrieve_logs_filter_by_start_date_success() {
        Log__c log = new Log__c();
        insert log;

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = REST_URI;
        DateTime dt = DateTime.now().addHours(-2);
        String dtString = dt.format(Constants.GLOBAL_VARIABLE.DATETIME_FORMAT);
        req.addParameter('startDate', dtString);
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        LogRestService.doGet();
        Test.stopTest();

        String jsonResponse = res.responseBody.toString();
        System.assertNotEquals(null, jsonResponse);

        Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);
        System.assertEquals(LogRestService.STATUS_SUCCESS, (String)result.get('status'));
        System.assertEquals(null, result.get('error'));
        System.assertNotEquals(null, (List<Object>)result.get('logs'));
        System.assertNotEquals(0, ((List<Object>)result.get('logs')).size());

    }

    @IsTest
    static void test_retrieve_logs_filter_by_start_date_fail() {
        Log__c log = new Log__c();
        insert log;

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = REST_URI;
        DateTime dt = DateTime.now().addDays(1);
        String dtString = dt.format(Constants.GLOBAL_VARIABLE.DATETIME_FORMAT);
        req.addParameter('startDate', dtString);
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        LogRestService.doGet();
        Test.stopTest();

        String jsonResponse = res.responseBody.toString();
        System.assertNotEquals(null, jsonResponse);

        Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);
        System.assertEquals(LogRestService.STATUS_SUCCESS, (String)result.get('status'));
        System.assertEquals(null, result.get('error'));
        System.assertNotEquals(null, (List<Object>)result.get('logs'));
        System.assertEquals(0, ((List<Object>)result.get('logs')).size());
    }

    @IsTest
    static void test_send_logs_broadcast() {
        Connected_Org__c corg = ConnectedOrgService.getConnectedOrgById(UserInfo.getOrganizationId().left(15));
        corg.Data_Direction__c = 'receiveFrom';
        update corg;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = REST_URI;
        req.addParameter(ConfigUtil.PARAMS_TYPE, ConfigUtil.TYPE_BROADCAST);
        req.httpMethod = 'POST';
        BroadcastService.IncomingData incomingData = new BroadcastService.IncomingData();
        Log__c log = new Log__c();
        log.Organization_Id__c = UserInfo.getOrganizationId().left(15);
        log.Post_Processing_Complete__c = true;
        incomingData.logs = new List<Log__c>{log};
        incomingData.organizationId = UserInfo.getOrganizationId().left(15);
        req.requestBody = Blob.valueOf(JSON.serialize(incomingData));
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        LogRestService.doPost();
        Test.stopTest();

        String jsonResponse = res.responseBody.toString();
        System.assertNotEquals(null, jsonResponse);
        System.assertEquals(1, [SELECT Id FROM Log__c].size());
    }

    @IsTest
    static void test_send_logs_passthrough_mode() {
        Connected_Org__c corg = ConnectedOrgService.getConnectedOrgById(UserInfo.getOrganizationId().left(15));
        corg.Data_Direction__c = 'receiveFrom';
        update corg;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = REST_URI;
        req.addParameter(ConfigUtil.PARAMS_TYPE, ConfigUtil.TYPE_PASSTHROUGH_MODE);
        req.httpMethod = 'POST';
        PassthroughtModeService.IncomingLogData incomingLogData = new PassthroughtModeService.IncomingLogData();
        Log__c log = new Log__c();
        log.Organization_Id__c = UserInfo.getOrganizationId().left(15);
        log.Post_Processing_Complete__c = true;
        incomingLogData.logs = new List<Log__c>{log};
        incomingLogData.organizationId = UserInfo.getOrganizationId().left(15);
        req.requestBody = Blob.valueOf(JSON.serialize(incomingLogData));
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        LogRestService.doPost();
        Test.stopTest();

        String jsonResponse = res.responseBody.toString();
        System.assertNotEquals(null, jsonResponse);
        System.assertEquals(1, [SELECT Id FROM Log__c].size());
    }

    @IsTest
    static void test_send_logs_passthrough_mode_avoid_callout_loop_exception() {
        Connected_Org__c corg = ConnectedOrgService.getConnectedOrgById(UserInfo.getOrganizationId().left(15));
        corg.Data_Direction__c = 'receiveFrom';
        update corg;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = REST_URI;
        req.addParameter(ConfigUtil.PARAMS_TYPE, ConfigUtil.TYPE_PASSTHROUGH_MODE);
        req.httpMethod = 'POST';
        PassthroughtModeService.IncomingLogData incomingLogData = new PassthroughtModeService.IncomingLogData();
        incomingLogData.logs = null;
        incomingLogData.organizationId = UserInfo.getOrganizationId().left(15);
        incomingLogData.inboundEmail = new Inbound_Email__c();
        incomingLogData.inboundEmail.From__c = 'test@test.com';
        incomingLogData.inboundEmail.Subject__c = 'An error occurred with your "some_labels" flow';
        incomingLogData.inboundEmail.Html_Body__c = String.valueOf(Test_LogService.getTestStub('FLOW_SAME_API_LABELS_ELEMENTS_STACKTRACE'));
        incomingLogData.inboundEmail.Pharos_Org_ID__c = UserInfo.getOrganizationId().left(15);
        req.requestBody = Blob.valueOf(JSON.serialize(incomingLogData));
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        LogRestService.doPost();
        Test.stopTest();

        Integer calloutsAfter = Limits.getCallouts();
        System.assertEquals(0, calloutsAfter);

        String jsonResponse = res.responseBody.toString();
        System.assertNotEquals(null, jsonResponse);
        System.assertEquals(1, [SELECT Id FROM Log__c].size());
    }

}