main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/RecordCount__c.field-meta.xml
<CustomField>
    <fullName>RecordCount__c</fullName>
    <label>Number of Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Event__c/fields/Records__c.field-meta.xml
<CustomField>
    <fullName>Records__c</fullName>
    <label>Records</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Functional Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Pharos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Email-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Lead</fullName>
            </value>
            <value>
                <fullName>Pharos Error</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>OmniStudio</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <label>Rule</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Rule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rule__c/fields/EventTimeInterval__c.field-meta.xml
<CustomField>
    <fullName>EventTimeInterval__c</fullName>
    <label>Event Time Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Archival</fullName>
            </value>
            <value>
                <fullName>JIRA Update</fullName>
            </value>
            <value>
                <fullName>Notification</fullName>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
            <value>
                <fullName>Limits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/EventRecordDetailsControllerTest.cls
@IsTest
private class EventRecordDetailsControllerTest {

	@TestSetup
	static void setupTestData() {
		Rule__c mr1 = new Rule__c();
		mr1.Active__c = true;
		mr1.Type__c = Constants.RULE_SOBJECT.TYPE_MONITORING;
		mr1.EventTimeInterval__c = 1*60;
		insert mr1;

		Log__c log = new Log__c();
		log.Category__c = 'TestCategory';
		log.Type__c = 'TestType' ;
		log.Area__c = 'Apex';
		log.Details__c = 'pass pass pass pass pass pass pass';
		insert log;

		Event__c event = new Event__c();
		event.Rule__c = mr1.Id;
		event.RecordCount__c = 1;
		event.Records__c = '{"":["' + log.Id + '"]}';
		insert event;
	}

	@IsTest
	static void test_event_getLogsData() {
		Event__c event = getEvent();
		
		Test.startTest();
		List<EventRecordDetailsController.LogData> result = EventRecordDetailsController.getLogsData(event.Id);
		Test.stopTest();

		Assert.areEqual(1, result.size(), 'Should return 1 log record');
	}

	@IsTest
	static void test_getLogsData_withListIdsRecords() {
		Log__c log = [SELECT Id FROM Log__c];
		Event__c event = getEvent();

		event.Records__c = JSON.serialize(new List<String>{ log.Id });
		update event;

		Test.startTest();
		List<EventRecordDetailsController.LogData> result = EventRecordDetailsController.getLogsData(event.Id);
		Test.stopTest();

		Assert.areEqual(1, result.size(), 'Should return 1 log record');
	}

	@IsTest
	static void test_getLogsData_emptyRecords() {
		Event__c event = getEvent();

		event.Records__c = '';
		update event;

		Test.startTest();
		List<EventRecordDetailsController.LogData> result = EventRecordDetailsController.getLogsData(event.Id);
		Test.stopTest();

		Assert.areEqual(0, result.size(), 'Should return empty list for empty Records__c');
	}

	@IsTest
	static void test_getLogsData_nullRecords() {
		Event__c event = getEvent();

		event.Records__c = null;
		update event;

		Test.startTest();
		List<EventRecordDetailsController.LogData> result = EventRecordDetailsController.getLogsData(event.Id);
		Test.stopTest();

		Assert.areEqual(0, result.size(), 'Should return empty list for null Records__c');
	}

	@IsTest
	static void test_constructor_withDevParameter() {
		Event__c event = getEvent();

		PageReference pageRef = Page.EventRecordDetails;
		pageRef.getParameters().put('recordId', event.Id);
		pageRef.getParameters().put('dev', 'true');
		Test.setCurrentPage(pageRef);

		Test.startTest();
		ApexPages.StandardController sc = new ApexPages.StandardController(event);
		EventRecordDetailsController controller = new EventRecordDetailsController(sc);
		Test.stopTest();

		Assert.areEqual(true, controller.isDev, 'isDev should be true when dev parameter is true');
		Assert.areNotEqual(null, controller.eventJson, 'eventJson should not be null');
		Assert.areNotEqual(null, controller.logData, 'logData should not be null');
		Assert.areNotEqual(null, controller.packageNamespace, 'packageNamespace should not be null');
		Assert.areNotEqual(null, EventRecordDetailsController.baseUrl, 'baseUrl should not be null');
	}

	@IsTest
	static void test_constructor_withoutDevParameter() {
		Event__c event = getEvent();

		PageReference pageRef = Page.EventRecordDetails;
		pageRef.getParameters().put('recordId', event.Id);
		Test.setCurrentPage(pageRef);

		Test.startTest();
		ApexPages.StandardController sc = new ApexPages.StandardController(event);
		EventRecordDetailsController controller = new EventRecordDetailsController(sc);
		Test.stopTest();

		Assert.areEqual(false, controller.isDev, 'isDev should be false when no dev parameter is provided');
		Assert.areNotEqual(null, controller.eventJson, 'eventJson should not be null');
		Assert.areNotEqual(null, controller.logData, 'logData should not be null');
	}

	@IsTest
	static void test_constructor_withDevParameterFalse() {
		Event__c event = getEvent();

		PageReference pageRef = Page.EventRecordDetails;
		pageRef.getParameters().put('recordId', event.Id);
		pageRef.getParameters().put('dev', 'false');
		Test.setCurrentPage(pageRef);

		Test.startTest();
		ApexPages.StandardController sc = new ApexPages.StandardController(event);
		EventRecordDetailsController controller = new EventRecordDetailsController(sc);
		Test.stopTest();

		Assert.areEqual(false, controller.isDev, 'isDev should be false when dev parameter is false');
	}

	@IsTest
	static void test_constructor_withCookie() {
		Event__c event = getEvent();

		PageReference pageRef = Page.EventRecordDetails;
		pageRef.getParameters().put('recordId', event.Id);
		Test.setCurrentPage(pageRef);

		// Set a cookie for development mode
		Cookie devCookie = new Cookie('a2developmentMode', 'true', null, -1, false);
		ApexPages.currentPage().setCookies(new Cookie[]{ devCookie });

		Test.startTest();
		ApexPages.StandardController sc = new ApexPages.StandardController(event);
		EventRecordDetailsController controller = new EventRecordDetailsController(sc);
		Test.stopTest();

		// Note: Cookie reading might not work in test context, so isDev will likely be false
		Assert.areNotEqual(null, controller.eventJson, 'eventJson should not be null');
	}

	private static Event__c getEvent() {
		return [SELECT Rule__c, RecordCount__c, Records__c FROM Event__c];
	}
}