main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Records__c.field-meta.xml
<CustomField>
    <fullName>Records__c</fullName>
    <label>Records</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Monitoring.recordType-meta.xml
<RecordType>
    <fullName>Monitoring</fullName>
    <active>true</active>
    <label>Monitoring</label>
</RecordType>

main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Email-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Lead</fullName>
            </value>
            <value>
                <fullName>Pharos Error</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>OmniStudio</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Created At</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Log__c/fields/Hash_1__c.field-meta.xml
<CustomField>
    <fullName>Hash_1__c</fullName>
    <label>Hash 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <label>Error</label>
</RecordType>

main/default/objects/Log__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <label>Rule</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Rule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rule__c/fields/AggregateInterval__c.field-meta.xml
<CustomField>
    <fullName>AggregateInterval__c</fullName>
    <label>Aggregate Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rule__c/fields/AggregateType__c.field-meta.xml
<CustomField>
    <fullName>AggregateType__c</fullName>
    <label>Aggregate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Count</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rule__c/fields/ComparisonOperator__c.field-meta.xml
<CustomField>
    <fullName>ComparisonOperator__c</fullName>
    <label>Comparison Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ComparisonOperator</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Rule__c/fields/EventTimeInterval__c.field-meta.xml
<CustomField>
    <fullName>EventTimeInterval__c</fullName>
    <label>Event Time Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rule__c/fields/FilterLogic__c.field-meta.xml
<CustomField>
    <fullName>FilterLogic__c</fullName>
    <label>Filter Logic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Rule__c/fields/Is_Not_Valid__c.field-meta.xml
<CustomField>
    <fullName>Is_Not_Valid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Not Valid</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Rule__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Spike</fullName>
            </value>
            <value>
                <fullName>Impact</fullName>
            </value>
            <value>
                <fullName>Frequency</fullName>
            </value>
            <value>
                <fullName>Regression</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Archival</fullName>
            </value>
            <value>
                <fullName>JIRA Update</fullName>
            </value>
            <value>
                <fullName>Notification</fullName>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
            <value>
                <fullName>Limits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/RuleFilter__c/RuleFilter__c.object-meta.xml
<CustomObject>
    <label>Rule Filter</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Rule Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/RuleFilter__c/fields/Comparison_Type__c.field-meta.xml
<CustomField>
    <fullName>Comparison_Type__c</fullName>
    <label>Comparison Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Value</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/RuleFilter__c/fields/ComparisonOperator__c.field-meta.xml
<CustomField>
    <fullName>ComparisonOperator__c</fullName>
    <label>Comparison Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equal</fullName>
            </value>
            <value>
                <fullName>Not equal</fullName>
            </value>
            <value>
                <fullName>Greater than</fullName>
            </value>
            <value>
                <fullName>Greater or equal</fullName>
            </value>
            <value>
                <fullName>Less than</fullName>
            </value>
            <value>
                <fullName>Less or equal</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Doesn&apos;t Contain</fullName>
            </value>
            <value>
                <fullName>Includes</fullName>
            </value>
            <value>
                <fullName>Excludes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/RuleFilter__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/RuleFilter__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/RuleFilter__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Filters</relationshipLabel>
    <relationshipName>RuleFilters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/EventsChartsWrapperControllerTest.cls
@IsTest
public with sharing class EventsChartsWrapperControllerTest {
    
    @TestSetup
    static void testSetup() {
        // Create Rule for Spike subtype manually to avoid caching issues
        Rule__c rule = new Rule__c();
        rule.Active__c = true;
        rule.Is_Not_Valid__c = false;
        rule.Index__c = 0;
        rule.Type__c = 'Monitoring';
        rule.Subtype__c = Constants.RULE_SOBJECT.SUB_TYPE_SPIKE;
        rule.Threshold__c = 10;
        rule.EventTimeInterval__c = 60;
        rule.AggregateInterval__c = 60;
        rule.AggregateType__c = 'Count';
        rule.ComparisonOperator__c = 'Greater or equal';
        rule.FilterLogic__c = '1';
        insert rule;
        
        // Create RuleFilter for Spike rule
        RuleFilter__c ruleFilter = new RuleFilter__c();
        ruleFilter.Rule__c = rule.Id;
        ruleFilter.Index__c = 1;
        ruleFilter.FieldName__c = ConfigUtil.nameSpacePrefix + 'Type__c';
        ruleFilter.ComparisonOperator__c = 'Not equal';
        ruleFilter.Value__c = 'notTestType';
        ruleFilter.Comparison_Type__c = 'Value';
        insert ruleFilter;
        
        // Create Rule for Impact subtype manually to avoid caching issues
        Rule__c impactRule = new Rule__c();
        impactRule.Active__c = true;
        impactRule.Is_Not_Valid__c = false;
        impactRule.Index__c = 1;
        impactRule.Type__c = 'Monitoring';
        impactRule.Subtype__c = Constants.RULE_SOBJECT.SUB_TYPE_IMPACT;
        impactRule.Threshold__c = 1;
        impactRule.EventTimeInterval__c = 30;
        impactRule.AggregateInterval__c = 30;
        impactRule.AggregateType__c = 'Count';
        impactRule.ComparisonOperator__c = 'Greater or equal';
        impactRule.FilterLogic__c = '2';
        insert impactRule;
        
        // Create RuleFilter for Impact rule (Field type for grouping)
        RuleFilter__c impactFilterField = new RuleFilter__c();
        impactFilterField.Rule__c = impactRule.Id;
        impactFilterField.Index__c = 1;
        impactFilterField.FieldName__c = ConfigUtil.nameSpacePrefix + 'Hash_1__c';
        impactFilterField.ComparisonOperator__c = 'Equal';
        impactFilterField.Value__c = '1';
        impactFilterField.Comparison_Type__c = 'Field';
        impactFilterField.Field_Type__c = 'STRING';
        insert impactFilterField;
        
        // Create RuleFilter for Impact rule (Value type for filtering)
        RuleFilter__c impactFilterValue = new RuleFilter__c();
        impactFilterValue.Rule__c = impactRule.Id;
        impactFilterValue.Index__c = 2;
        impactFilterValue.FieldName__c = ConfigUtil.nameSpacePrefix + 'Type__c';
        impactFilterValue.ComparisonOperator__c = 'Equal';
        impactFilterValue.Value__c = 'ERROR';
        impactFilterValue.Comparison_Type__c = 'Value';
        insert impactFilterValue;
        
        // Create Logs for timing and chart data
        // Use time around now so Events can find them
        List<Log__c> logs = new List<Log__c>();
        DateTime baseTime = DateTime.now().addMinutes(-30); // 30 minutes ago
        for (Integer i = 0; i < 10; i++) {
            Log__c log = new Log__c();
            log.Type__c = 'ERROR';
            log.Category__c = 'Apex';
            log.Summary__c = 'Test Error ' + i;
            log.Hash_1__c = 'hash' + i;
            log.Created_At__c = baseTime.addMinutes(i * 5);
            logs.add(log);
        }
        insert logs;
        
        // Create Event with Map format for Records__c using real log IDs
        Map<String, List<Id>> recordsMap = new Map<String, List<Id>>();
        List<Id> logIds = new List<Id>();
        for (Integer i = 0; i < 3 && i < logs.size(); i++) {
            logIds.add(logs[i].Id);
        }
        recordsMap.put('Log__c', logIds);
        
        // Create Event for Spike rule with time matching logs
        Event__c event = new Event__c();
        event.Rule__c = rule.Id;
        event.Records__c = JSON.serialize(recordsMap);
        insert event;
        
        // Update CreatedDate to match log timeframe (middle of log range)
        Test.setCreatedDate(event.Id, baseTime.addMinutes(25));
        
        // Create Event for Impact rule with time matching logs
        Event__c impactEvent = new Event__c();
        impactEvent.Rule__c = impactRule.Id;
        impactEvent.Records__c = JSON.serialize(recordsMap);
        insert impactEvent;
        
        // Update CreatedDate to match log timeframe
        Test.setCreatedDate(impactEvent.Id, baseTime.addMinutes(25));
    }
    
    @IsTest
    static void test_constructor_withDevParameter() {
        Rule__c spikeRule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        Event__c event = [SELECT Id FROM Event__c WHERE Rule__c = :spikeRule.Id LIMIT 1];
        
        PageReference pageRef = Page.EventsChartsWrapper;
        pageRef.getParameters().put('recordId', event.Id);
        pageRef.getParameters().put('dev', 'true');
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        ApexPages.StandardController stdController = new ApexPages.StandardController(event);
        EventsChartsWrapperController controller = new EventsChartsWrapperController(stdController);
        Test.stopTest();
        
        Assert.isTrue(controller.isDev, 'isDev should be true when dev parameter is set');
        Assert.areNotEqual(null, controller.currentEvent, 'currentEvent should not be null');
        Assert.areNotEqual(null, controller.currentRule, 'currentRule should not be null');
        Assert.areNotEqual(null, controller.packageNamespace, 'packageNamespace should not be null');
        Assert.areNotEqual(null, controller.userTimezoneOffset, 'userTimezoneOffset should not be null');
    }
    
    @IsTest
    static void test_constructor_withDevCookie() {
        Rule__c spikeRule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        Event__c event = [SELECT Id FROM Event__c WHERE Rule__c = :spikeRule.Id LIMIT 1];
        
        PageReference pageRef = Page.EventsChartsWrapper;
        pageRef.getParameters().put('recordId', event.Id);
        Test.setCurrentPage(pageRef);
        
        Cookie devCookie = new Cookie('a2developmentMode', 'true', null, -1, false);
        ApexPages.currentPage().setCookies(new Cookie[]{devCookie});
        
        Test.startTest();
        ApexPages.StandardController stdController = new ApexPages.StandardController(event);
        EventsChartsWrapperController controller = new EventsChartsWrapperController(stdController);
        Test.stopTest();
        
        Assert.isTrue(controller.isDev, 'isDev should be true when dev cookie is set');
    }
    
    @IsTest
    static void test_constructor_withoutDevParameterOrCookie() {
        Rule__c spikeRule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        Event__c event = [SELECT Id FROM Event__c WHERE Rule__c = :spikeRule.Id LIMIT 1];
        
        PageReference pageRef = Page.EventsChartsWrapper;
        pageRef.getParameters().put('recordId', event.Id);
        Test.setCurrentPage(pageRef);
        
        Test.startTest();
        ApexPages.StandardController stdController = new ApexPages.StandardController(event);
        EventsChartsWrapperController controller = new EventsChartsWrapperController(stdController);
        Test.stopTest();
        
        Assert.isFalse(controller.isDev, 'isDev should be false when no dev parameter or cookie');
    }
    
    @IsTest
    static void test_getEvents_with7Days() {
        Rule__c rule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        
        Test.startTest();
        String result = EventsChartsWrapperController.getEvents(7, rule.Id);
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
        List<Event__c> events = (List<Event__c>)JSON.deserialize(result, List<Event__c>.class);
        Assert.areNotEqual(null, events, 'Events list should not be null');
        Assert.areEqual(1, events.size(), 'Should return 1 event for Spike rule');
    }
    
    @IsTest
    static void test_getEvents_with30Days() {
        Rule__c rule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        
        Test.startTest();
        String result = EventsChartsWrapperController.getEvents(30, rule.Id);
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
        List<Event__c> events = (List<Event__c>)JSON.deserialize(result, List<Event__c>.class);
        Assert.areNotEqual(null, events, 'Events list should not be null');
        Assert.areEqual(1, events.size(), 'Should return 1 event for Spike rule');
    }
    
    @IsTest
    static void test_getEvents_with60Days() {
        Rule__c rule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        
        Test.startTest();
        String result = EventsChartsWrapperController.getEvents(60, rule.Id);
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
        List<Event__c> events = (List<Event__c>)JSON.deserialize(result, List<Event__c>.class);
        Assert.areNotEqual(null, events, 'Events list should not be null');
        Assert.areEqual(1, events.size(), 'Should return 1 event for Spike rule');
    }
    
    @IsTest
    static void test_getEvents_with180Days() {
        Rule__c rule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        
        Test.startTest();
        String result = EventsChartsWrapperController.getEvents(180, rule.Id);
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
        List<Event__c> events = (List<Event__c>)JSON.deserialize(result, List<Event__c>.class);
        Assert.areNotEqual(null, events, 'Events list should not be null');
        Assert.areEqual(1, events.size(), 'Should return 1 event for Spike rule');
    }
    
    @IsTest
    static void test_getEvents_withInvalidDays() {
        Rule__c rule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        
        Test.startTest();
        String result = EventsChartsWrapperController.getEvents(99, rule.Id);
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null, should default to 30 days');
        List<Event__c> events = (List<Event__c>)JSON.deserialize(result, List<Event__c>.class);
        Assert.areNotEqual(null, events, 'Events list should not be null');
        Assert.areEqual(1, events.size(), 'Should return 1 event for Spike rule');
    }
    
    @IsTest
    static void test_getTimingLogs_with10Minutes() {
        DateTime eventTime = DateTime.now();
        
        Test.startTest();
        String result = EventsChartsWrapperController.getTimingLogs(eventTime, 10);
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
        List<Log__c> logs = (List<Log__c>)JSON.deserialize(result, List<Log__c>.class);
        Assert.areNotEqual(null, logs, 'Logs list should not be null');
    }
    
    @IsTest
    static void test_getTimingLogs_with30Minutes() {
        DateTime eventTime = DateTime.now();
        
        Test.startTest();
        String result = EventsChartsWrapperController.getTimingLogs(eventTime, 30);
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
    }
    
    @IsTest
    static void test_getTimingLogs_with60Minutes() {
        DateTime eventTime = DateTime.now();
        
        Test.startTest();
        String result = EventsChartsWrapperController.getTimingLogs(eventTime, 60);
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
    }
    
    @IsTest
    static void test_getTimingLogs_withInvalidRange() {
        DateTime eventTime = DateTime.now();
        
        Test.startTest();
        String result = EventsChartsWrapperController.getTimingLogs(eventTime, 99);
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null, should default to 10 minutes');
    }
    
    @IsTest
    static void test_remoteActionHandler_getOccurrenceEvents() {
        Rule__c spikeRule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        Event__c event = [SELECT Id, Rule__c FROM Event__c WHERE Rule__c = :spikeRule.Id LIMIT 1];
        
        Map<String, Object> input = new Map<String, Object>{
            'method' => 'getOccurrenceEvents',
            'data' => new Map<String, Object>{
                'eventId' => event.Id,
                'showDays' => 7
            }
        };
        
        Test.startTest();
        String result = EventsChartsWrapperController.remoteActionHandler(JSON.serialize(input));
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
        Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(result);
        Assert.areNotEqual(null, response.get('data'), 'Response data should not be null');
    }
    
    @IsTest
    static void test_remoteActionHandler_getEventRecords_spike() {
        TestDataFactory.enableMaxArchivalRules();
        
        // Get Spike rule and its event (only one Spike event exists)
        Rule__c spikeRule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        Event__c event = [SELECT Id, Records__c FROM Event__c WHERE Rule__c = :spikeRule.Id LIMIT 1];

        Map<String, Object> input = new Map<String, Object>{
            'method' => 'getEventRecords',
            'data' => new Map<String, Object>{
                'eventId' => event.Id,
                'range' => 60
            }
        };
        
        Test.startTest();
        String result = EventsChartsWrapperController.remoteActionHandler(JSON.serialize(input));
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
        Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(result);
        Assert.areNotEqual(null, response.get('data'), 'Response data should not be null');
    }
    
    @IsTest
    static void test_remoteActionHandler_getEventRecords_impact() {
        TestDataFactory.enableMaxArchivalRules();
        
        // Get Impact rule and its event (only one Impact event exists)
        Rule__c impactRule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_IMPACT LIMIT 1];
        Event__c event = [SELECT Id, Records__c FROM Event__c WHERE Rule__c = :impactRule.Id LIMIT 1];

        Map<String, Object> input = new Map<String, Object>{
            'method' => 'getEventRecords',
            'data' => new Map<String, Object>{
                'eventId' => event.Id,
                'range' => 30
            }
        };
        
        Test.startTest();
        String result = EventsChartsWrapperController.remoteActionHandler(JSON.serialize(input));
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
        Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(result);
        Assert.areNotEqual(null, response.get('data'), 'Response data should not be null');
    }
    
    @IsTest
    static void test_remoteActionHandler_getTimingLogs() {
        Rule__c spikeRule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        Event__c event = [SELECT Id FROM Event__c WHERE Rule__c = :spikeRule.Id LIMIT 1];

        Map<String, Object> input = new Map<String, Object>{
            'method' => 'getTimingLogs',
            'data' => new Map<String, Object>{
                'eventId' => event.Id,
                'range' => 10
            }
        };
        
        Test.startTest();
        String result = EventsChartsWrapperController.remoteActionHandler(JSON.serialize(input));
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
        Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(result);
        Assert.areNotEqual(null, response.get('data'), 'Response data should not be null');
    }
    
    @IsTest
    static void test_remoteActionHandler_invalidMethod() {
        Rule__c spikeRule = [SELECT Id FROM Rule__c WHERE Subtype__c = :Constants.RULE_SOBJECT.SUB_TYPE_SPIKE LIMIT 1];
        Event__c event = [SELECT Id FROM Event__c WHERE Rule__c = :spikeRule.Id LIMIT 1];

        Map<String, Object> input = new Map<String, Object>{
            'method' => 'invalidMethod',
            'data' => new Map<String, Object>{
                'eventId' => event.Id
            }
        };
        
        Test.startTest();
        String result = EventsChartsWrapperController.remoteActionHandler(JSON.serialize(input));
        Test.stopTest();
        
        Assert.areNotEqual(null, result, 'Result should not be null');
        Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(result);
        Assert.areNotEqual(null, response.get('error'), 'Response should contain error');
        Assert.areEqual('Action not found', (String)response.get('error'), 'Error message should indicate action not found');
    }
    
    @IsTest
    static void test_chartData_constructor() {
        Test.startTest();
        EventsChartsWrapperController.ChartData chartData = new EventsChartsWrapperController.ChartData();
        Test.stopTest();
        
        Assert.areNotEqual(null, chartData.mapIntervals, 'mapIntervals should not be null');
        Assert.areNotEqual(null, chartData.logs, 'logs should not be null');
        Assert.areEqual(0, chartData.countLogs, 'countLogs should be 0');
    }
    
    @IsTest
    static void test_chartDataInterval_constructor() {
        Test.startTest();
        EventsChartsWrapperController.ChartDataInterval interval = new EventsChartsWrapperController.ChartDataInterval();
        Test.stopTest();
        
        Assert.areNotEqual(null, interval.logValues, 'logValues should not be null');
        Assert.areEqual(0, interval.value, 'value should be 0');
    }
    
    @IsTest
    static void test_remoteActionResponse_class() {
        Test.startTest();
        EventsChartsWrapperController.RemoteActionResponse response = new EventsChartsWrapperController.RemoteActionResponse();
        response.params = 'test params';
        response.data = 'test data';
        response.error = 'test error';
        response.stack = 'test stack';
        Test.stopTest();
        
        Assert.areEqual('test params', response.params, 'params should be set correctly');
        Assert.areEqual('test data', response.data, 'data should be set correctly');
        Assert.areEqual('test error', response.error, 'error should be set correctly');
        Assert.areEqual('test stack', response.stack, 'stack should be set correctly');
    }
}