main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/RecordCount__c.field-meta.xml
<CustomField>
    <fullName>RecordCount__c</fullName>
    <label>Number of Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Event__c/fields/Rule_Description__c.field-meta.xml
<CustomField>
    <fullName>Rule_Description__c</fullName>
    <formula>Rule__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rule Description</label>
    <type>Text</type>
</CustomField>

main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>ISS-{00000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Issue__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Log__r.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

main/default/objects/Issue__c/fields/Functional_Area__c.field-meta.xml
<CustomField>
    <fullName>Functional_Area__c</fullName>
    <formula>TEXT(Log__r.Area__c)</formula>
    <label>Functional Area</label>
    <type>Text</type>
</CustomField>

main/default/objects/Issue__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Issue__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <label>Organization Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Triaged</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Issue__c/recordTypes/Issue.recordType-meta.xml
<RecordType>
    <fullName>Issue</fullName>
    <active>true</active>
    <label>Issue</label>
</RecordType>

main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Functional Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Pharos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Email-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Lead</fullName>
            </value>
            <value>
                <fullName>Pharos Error</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>OmniStudio</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Issue__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <label>Error</label>
</RecordType>

main/default/objects/Log__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/pharos__Event__c/pharos__Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/pharos__Event__c/fields/pharos__RecordCount__c.field-meta.xml
<CustomField>
    <fullName>pharos__RecordCount__c</fullName>
    <label>Number of Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/pharos__Event__c/fields/pharos__Rule_Description__c.field-meta.xml
<CustomField>
    <fullName>pharos__Rule_Description__c</fullName>
    <formula>pharos__Rule__r.pharos__Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rule Description</label>
    <type>Text</type>
</CustomField>

main/default/objects/pharos__Issue__c/pharos__Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>ISS-{00000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/pharos__Issue__c/fields/pharos__Category__c.field-meta.xml
<CustomField>
    <fullName>pharos__Category__c</fullName>
    <formula>TEXT(pharos__Log__r.pharos__Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

main/default/objects/pharos__Issue__c/fields/pharos__Description__c.field-meta.xml
<CustomField>
    <fullName>pharos__Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/pharos__Issue__c/fields/pharos__Functional_Area__c.field-meta.xml
<CustomField>
    <fullName>pharos__Functional_Area__c</fullName>
    <formula>TEXT(pharos__Log__r.pharos__Area__c)</formula>
    <label>Functional Area</label>
    <type>Text</type>
</CustomField>

main/default/objects/pharos__Issue__c/fields/pharos__Log__c.field-meta.xml
<CustomField>
    <fullName>pharos__Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log</label>
    <referenceTo>pharos__Log__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/pharos__Issue__c/fields/pharos__Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>pharos__Organization_Name__c</fullName>
    <label>Organization Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/pharos__Issue__c/fields/pharos__Status__c.field-meta.xml
<CustomField>
    <fullName>pharos__Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Triaged</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/pharos__Issue__c/fields/pharos__Summary__c.field-meta.xml
<CustomField>
    <fullName>pharos__Summary__c</fullName>
    <label>Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/pharos__Log__c/pharos__Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/pharos__Log__c/fields/pharos__Category__c.field-meta.xml
<CustomField>
    <fullName>pharos__Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Email-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Lead</fullName>
            </value>
            <value>
                <fullName>Pharos Error</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>OmniStudio</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/pharos__Log__c/fields/pharos__Issue__c.field-meta.xml
<CustomField>
    <fullName>pharos__Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>pharos__Issue__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/pharos__Log__c/fields/pharos__Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>pharos__Organization_Name__c</fullName>
    <label>Organization Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/pharos__Log__c/fields/pharos__Summary__c.field-meta.xml
<CustomField>
    <fullName>pharos__Summary__c</fullName>
    <label>Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/pharos__Trace_Result__c/pharos__Trace_Result__c.object-meta.xml
<CustomObject>
    <label>Trace Result</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Trace Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trace Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/pharos__Trace_Result__c/fields/pharos__Issue__c.field-meta.xml
<CustomField>
    <fullName>pharos__Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>pharos__Issue__c</referenceTo>
    <relationshipLabel>Trace Results</relationshipLabel>
    <relationshipName>Trace_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Trace_Result__c/Trace_Result__c.object-meta.xml
<CustomObject>
    <label>Trace Result</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Trace Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trace Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Trace_Result__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Issue__c</referenceTo>
    <relationshipLabel>Trace Results</relationshipLabel>
    <relationshipName>Trace_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/Templates.cls
public with sharing class Templates {

    public static final EventSObject EVENT_SOBJECT {
        get { return EVENT_SOBJECT == null ? (EVENT_SOBJECT = new EventSObject()) : EVENT_SOBJECT; }
        private set;
    }
    
    public static final IssueSObject ISSUE_SOBJECT {
        get { return ISSUE_SOBJECT == null ? (ISSUE_SOBJECT = new IssueSObject()) : ISSUE_SOBJECT; }
        private set;
    }

    public static final LogSObject LOG_SOBJECT {
        get { return LOG_SOBJECT == null ? (LOG_SOBJECT = new LogSObject()) : LOG_SOBJECT; }
        private set;
    }

    public static final TraceResultSObject TRACE_RESULT_SOBJECT {
        get { return TRACE_RESULT_SOBJECT == null ? (TRACE_RESULT_SOBJECT = new TraceResultSObject()) : TRACE_RESULT_SOBJECT; }
        private set;
    }

    public inherited sharing class EventSObject {
        private String defaultMonitoringActionSubject = 'New Critical Event: \'{!\'{0}.{1}\'}\'';
        private String defaultMonitoringActionBody = '\'{\'!{0}.Link\'}\'\n\'{\'!{0}.{1}\'}\' records in the triggered event.\nDetails:\n \'{\'!{0}.{2}\'}\'\n';

        /*
        [Subject]
        New Critical Event: {!pharos__Event__c.pharos__Rule_Description__c}

        [Body]
        {!pharos__Event__c.Link}
        {!pharos__Event__c.pharos__RecordCount__c} records in the triggered event.
        Details:
        {!pharos__Event__c.Event_Details__c}
        */
        public final Map<String, String> DEFAULT_MONITORING_ACTION = new Map<String, String>{
            'subject' => String.format(defaultMonitoringActionSubject,
                new List<String> {
                    Schema.SObjectType.Event__c.getName(),
                    Schema.SObjectType.Event__c.fields.Rule_Description__c.getName()
                }),
            'body' => String.format(defaultMonitoringActionBody,
                new List<String> {
                    Schema.SObjectType.Event__c.getName(),
                    Schema.SObjectType.Event__c.fields.RecordCount__c.getName(),
                    Schema.SObjectType.Event__c.fields.Event_Details__c.getName()
                })
        };

        /*
        [Webhook Body Template]
        {
          "event": "critical_event",
          "rule": "{!pharos__Event__c.pharos__Rule_Description__c}",
          "record_count": "{!pharos__Event__c.pharos__RecordCount__c}",
          "details": "{!pharos__Event__c.Event_Details__c}",
          "link": "{!pharos__Event__c.Link}"
        }
        */
        public final Map<String, String> DEFAULT_WEBHOOK_ACTION = new Map<String, String>{
            'body' => '{\n' +
                '  "event": "critical_event",\n' +
                '  "rule": "{!' + Schema.SObjectType.Event__c.getName() + '.' + Schema.SObjectType.Event__c.fields.Rule_Description__c.getName() + '}",\n' +
                '  "record_count": "{!' + Schema.SObjectType.Event__c.getName() + '.' + Schema.SObjectType.Event__c.fields.RecordCount__c.getName() + '}",\n' +
                '  "details": "{!' + Schema.SObjectType.Event__c.getName() + '.' + Schema.SObjectType.Event__c.fields.Event_Details__c.getName() + '}",\n' +
                '  "link": "{!' + Schema.SObjectType.Event__c.getName() + '.Link}"\n' +
                '}'
        };
    }

    public inherited sharing class IssueSObject {
        private String defaultNotificationSubject = 'New \'{!\'{0}.{1}\'}\' Issue in \'{!\'{0}.{2}\'}\':  \'{!\'{0}.{3}\'}\'';
        private String defaultNotificationBody = '\'{\'!{0}.Link\'}\'\n' +
            'Functional Area: \'{\'!{0}.{1}\'}\'\n' +
            '\'{\'!{0}.{2}\'}\'\n';

        /*
        [Subject]
        New {!pharos__Issue__c.pharos__Category__c} Issue in {!pharos__Issue__c.pharos__Organization_Name__c}: {!pharos__Issue__c.pharos__Summary__c}

        [Body]
        {!pharos__Issue__c.Link}
        Functional Area: {!pharos__Issue__c.pharos__Functional_Area__c}
        {!pharos__Issue__c.pharos__Description__c}
        */
        public final Map<String, String> DEFAULT_NOTIFICATION = new Map<String, String>{
            'subject' => String.format(defaultNotificationSubject,
                new List<String> {
                    Schema.SObjectType.Issue__c.getName(),
                    Schema.SObjectType.Issue__c.fields.Category__c.getName(),
                    Schema.SObjectType.Issue__c.fields.Organization_Name__c.getName(),
                    Schema.SObjectType.Issue__c.fields.Summary__c.getName()
                }),
            'body' => String.format(defaultNotificationBody,
                new List<String> {
                    Schema.SObjectType.Issue__c.getName(),
                    Schema.SObjectType.Issue__c.fields.Functional_Area__c.getName(),
                    Schema.SObjectType.Issue__c.fields.Description__c.getName()
                })
        };

        private String defaultJiraActionSubject = 'New Issue in  \'{!\'{0}.{1}\'}\' : \'{!\'{0}.{2}\'}\'';
        private String defaultJiraActionBody = '\'{\'!{0}.Link\'}\'\nDetails: \'{\'!{0}.{1}\'}\'\n';

        /*
        [Subject]
        New Issue in {!pharos__Issue__c.pharos__Organization_Name__c}: {!pharos__Issue__c.pharos__Summary__c}

        [Body]
        {!pharos__Issue__c.Link}
        Details: {!pharos__Issue__c.pharos__Description__c}
        */
        public final Map <String, String> DEFAULT_JIRA_ACTION = new Map<String, String>{
            'subject' => String.format(defaultJiraActionSubject,
                new List<String> {
                    Schema.SObjectType.Issue__c.getName(),
                    Schema.SObjectType.Issue__c.fields.Organization_Name__c.getName(),
                    Schema.SObjectType.Issue__c.fields.Summary__c.getName()
                }),
            'body' => String.format(defaultJiraActionBody,
                new List<String> {
                    Schema.SObjectType.Issue__c.getName(),
                    Schema.SObjectType.Issue__c.fields.Description__c.getName()
                })
        };

        private String defaultTicketCommentActionSubject = null;
        private String defaultTicketCommentActionBody = '\'{\'!{0}.Link\'}\'\nDetails: \'{\'!{0}.{1}\'}\'\n';

        /*
        [Subject]
        null

        [Body]
        {!pharos__Issue__c.Link}
        Details: {!pharos__Issue__c.pharos__Description__c}
        */
        public final Map<String, String> DEFAULT_TICKET_COMMENT_ACTION = new Map<String, String>{
            'subject' => defaultTicketCommentActionSubject,
            'body' => String.format(defaultTicketCommentActionBody,
                new List<String> {
                    Schema.SObjectType.Issue__c.getName(),
                    Schema.SObjectType.Issue__c.fields.Description__c.getName()
            })
        };

        /*
        [Webhook Body Template - Create]
        {
          "event": "new_issue",
          "category": "{!pharos__Issue__c.pharos__Category__c}",
          "organization": "{!pharos__Issue__c.pharos__Organization_Name__c}",
          "summary": "{!pharos__Issue__c.pharos__Summary__c}",
          "functional_area": "{!pharos__Issue__c.pharos__Functional_Area__c}",
          "description": "{!pharos__Issue__c.pharos__Description__c}",
          "link": "{!pharos__Issue__c.Link}"
        }
        */
        public final Map<String, String> DEFAULT_WEBHOOK_ACTION = new Map<String, String>{
            'body' => '{\n' +
                '  "event": "new_issue",\n' +
                '  "category": "{!' + Schema.SObjectType.Issue__c.getName() + '.' + Schema.SObjectType.Issue__c.fields.Category__c.getName() + '}",\n' +
                '  "organization": "{!' + Schema.SObjectType.Issue__c.getName() + '.' + Schema.SObjectType.Issue__c.fields.Organization_Name__c.getName() + '}",\n' +
                '  "summary": "{!' + Schema.SObjectType.Issue__c.getName() + '.' + Schema.SObjectType.Issue__c.fields.Summary__c.getName() + '}",\n' +
                '  "functional_area": "{!' + Schema.SObjectType.Issue__c.getName() + '.' + Schema.SObjectType.Issue__c.fields.Functional_Area__c.getName() + '}",\n' +
                '  "description": "{!' + Schema.SObjectType.Issue__c.getName() + '.' + Schema.SObjectType.Issue__c.fields.Description__c.getName() + '}",\n' +
                '  "link": "{!' + Schema.SObjectType.Issue__c.getName() + '.Link}"\n' +
                '}'
        };

        /*
        [Webhook Body Template - Update]
        {
          "event": "issue_updated",
          "category": "{!pharos__Issue__c.pharos__Category__c}",
          "status": "{!pharos__Issue__c.pharos__Status__c}",
          "summary": "{!pharos__Issue__c.pharos__Summary__c}",
          "description": "{!pharos__Issue__c.pharos__Description__c}",
          "link": "{!pharos__Issue__c.Link}"
        }
        */
        public final Map<String, String> DEFAULT_WEBHOOK_UPDATE_ACTION = new Map<String, String>{
            'body' => '{\n' +
                '  "event": "issue_updated",\n' +
                '  "category": "{!' + Schema.SObjectType.Issue__c.getName() + '.' + Schema.SObjectType.Issue__c.fields.Category__c.getName() + '}",\n' +
                '  "status": "{!' + Schema.SObjectType.Issue__c.getName() + '.' + Schema.SObjectType.Issue__c.fields.Status__c.getName() + '}",\n' +
                '  "summary": "{!' + Schema.SObjectType.Issue__c.getName() + '.' + Schema.SObjectType.Issue__c.fields.Summary__c.getName() + '}",\n' +
                '  "description": "{!' + Schema.SObjectType.Issue__c.getName() + '.' + Schema.SObjectType.Issue__c.fields.Description__c.getName() + '}",\n' +
                '  "link": "{!' + Schema.SObjectType.Issue__c.getName() + '.Link}"\n' +
                '}'
        };
    }

    public inherited sharing class LogSObject {
        private String defaultNotificationSubject = 'New \'{!\'{0}.{1}\'}\' Log in \'{!\'{0}.{2}\'}\': \'{!\'{0}.{3}\'}\'';
        private String defaultNotificationBody = '\'{\'!{0}.Link\'}\'\n' +
            'Functional Area: \'{\'!{0}.{1}\'}\'\n' +
            'Type: \'{\'!{0}.{2}\'}\'\n' +
            '\'{\'!{0}.{3}\'}\'\n';
                
        /*
        [Subject]
        New {!pharos__Log__c.pharos__Category__c} Log in {!pharos__Log__c.pharos__Organization_Name__c}: {!pharos__Log__c.pharos__Summary__c}
        
        [Body]
        {!pharos__Log__c.Link}
        Functional Area: {!pharos__Log__c.pharos__Area__c} 
        Type: {!pharos__Log__c.pharos__Type__c}
        {!pharos__Log__c.pharos__Details__c}
        */
        public final Map<String, String> DEFAULT_NOTIFICATION = new Map<String, String>{
            'subject' => String.format(defaultNotificationSubject,
                new List<String> {
                    Schema.SObjectType.Log__c.getName(),
                    Schema.SObjectType.Log__c.fields.Category__c.getName(),
                    Schema.SObjectType.Log__c.fields.Organization_Name__c.getName(),
                    Schema.SObjectType.Log__c.fields.Summary__c.getName()
                }),
            'body' => String.format(defaultNotificationBody,
                new List<String> {
                    Schema.SObjectType.Log__c.getName(),
                    Schema.SObjectType.Log__c.fields.Area__c.getName(),
                    Schema.SObjectType.Log__c.fields.Type__c.getName(),
                    Schema.SObjectType.Log__c.fields.Details__c.getName()
                })
        };

        private String defaultJiraActionSubject = 'New Error in  \'{!\'{0}.{1}\'}\' : \'{!\'{0}.{2}\'}\'';
        private String defaultJiraActionBody = '\'{\'!{0}.Link\'}\'\nCategory: \'{\'!{0}.{1}\'}\'\nType: \'{\'!{0}.{2}\'}\'\nArea: \'{\'!{0}.{3}\'}\' \'{\'!{0}.{4}\'}\'';

        /*
        [Subject]
        New Error in {!pharos__Log__c.pharos__Organization_Name__c} : {!pharos__Log__c.pharos__Summary__c}
        
        [Body]
        {!pharos__Log__c.Link}
        Category: {!pharos__Log__c.pharos__Category__c}
        Type: {!pharos__Log__c.pharos__Type__c}
        Area: {!pharos__Log__c.pharos__Area__c} 
        {!pharos__Log__c.pharos__Details__c}
        */
        public final Map <String, String> DEFAULT_JIRA_ACTION = new Map<String, String>{
            'subject' => String.format(defaultJiraActionSubject,
                new List<String> {
                    Schema.SObjectType.Log__c.getName(),
                    Schema.SObjectType.Log__c.fields.Organization_Name__c.getName(),
                    Schema.SObjectType.Log__c.fields.Summary__c.getName()
                }),
            'body' => String.format(defaultJiraActionBody,
                new List<String> {
                    Schema.SObjectType.Log__c.getName(),
                    Schema.SObjectType.Log__c.fields.Category__c.getName(),
                    Schema.SObjectType.Log__c.fields.Type__c.getName(),
                    Schema.SObjectType.Log__c.fields.Area__c.getName(),
                    Schema.SObjectType.Log__c.fields.Details__c.getName()
                })
        };

        /*
        [Webhook Body Template]
        {
          "event": "new_log",
          "category": "{!pharos__Log__c.pharos__Category__c}",
          "type": "{!pharos__Log__c.pharos__Type__c}",
          "organization": "{!pharos__Log__c.pharos__Organization_Name__c}",
          "summary": "{!pharos__Log__c.pharos__Summary__c}",
          "area": "{!pharos__Log__c.pharos__Area__c}",
          "details": "{!pharos__Log__c.pharos__Details__c}",
          "link": "{!pharos__Log__c.Link}"
        }
        */
        public final Map<String, String> DEFAULT_WEBHOOK_ACTION = new Map<String, String>{
            'body' => '{\n' +
                '  "event": "new_log",\n' +
                '  "category": "{!' + Schema.SObjectType.Log__c.getName() + '.' + Schema.SObjectType.Log__c.fields.Category__c.getName() + '}",\n' +
                '  "type": "{!' + Schema.SObjectType.Log__c.getName() + '.' + Schema.SObjectType.Log__c.fields.Type__c.getName() + '}",\n' +
                '  "organization": "{!' + Schema.SObjectType.Log__c.getName() + '.' + Schema.SObjectType.Log__c.fields.Organization_Name__c.getName() + '}",\n' +
                '  "summary": "{!' + Schema.SObjectType.Log__c.getName() + '.' + Schema.SObjectType.Log__c.fields.Summary__c.getName() + '}",\n' +
                '  "area": "{!' + Schema.SObjectType.Log__c.getName() + '.' + Schema.SObjectType.Log__c.fields.Area__c.getName() + '}",\n' +
                '  "details": "{!' + Schema.SObjectType.Log__c.getName() + '.' + Schema.SObjectType.Log__c.fields.Details__c.getName() + '}",\n' +
                '  "link": "{!' + Schema.SObjectType.Log__c.getName() + '.Link}"\n' +
                '}'
        };
    }

    public inherited sharing class TraceResultSObject {
        private String defaultNotificationSubject = 'New Trace Result available for Issue \'{!\'{0}.{1}.{2}\'}\' : \'{!\'{0}.{1}.{3}\'}\'';
        private String defaultNotificationBody = 'Access the Trace Result here: \'{!\'{0}.Link\'}\'\nCategory: \'{\'!{0}.{1}.{2}\'}\'\n Functional Area: \'{\'!{0}.{1}.{3}\'}\'';

        /*
        [Subject]
        New Trace Result available for Issue {!pharos__Trace_Result__c.pharos__Issue__r.Name} : {!pharos__Trace_Result__c.pharos__Issue__r.pharos__Summary__c}
        
        [Body]
        Access the Trace Result here: {!pharos__Trace_Result__c.Link}
        Category: {!pharos__Trace_Result__c.pharos__Issue__r.pharos__Category__c}
        Functional Area: {!pharos__Trace_Result__c.pharos__Issue__r.pharos__Functional_Area__c}
        */
        public final Map<String, String> DEFAULT_NOTIFICATION = new Map<String, String>{
            'subject' => String.format(defaultNotificationSubject,
                new List<String> {
                    Schema.SObjectType.Trace_Result__c.getName(),
                    Schema.SObjectType.Trace_Result__c.fields.Issue__c.getRelationshipName(),
                    Schema.SObjectType.Issue__c.fields.Name.getName(),
                    Schema.SObjectType.Issue__c.fields.Summary__c.getName()
                }),
            'body' => String.format(defaultNotificationBody,
                new List<String> {
                    Schema.SObjectType.Trace_Result__c.getName(),
                    Schema.SObjectType.Trace_Result__c.fields.Issue__c.getRelationshipName(),
                    Schema.SObjectType.Issue__c.fields.Category__c.getName(),
                    Schema.SObjectType.Issue__c.fields.Functional_Area__c.getName()
                })
        };

        /*
        [Webhook Body Template]
        {
          "event": "trace_result_available",
          "issue_name": "{!pharos__Trace_Result__c.pharos__Issue__r.Name}",
          "issue_summary": "{!pharos__Trace_Result__c.pharos__Issue__r.pharos__Summary__c}",
          "category": "{!pharos__Trace_Result__c.pharos__Issue__r.pharos__Category__c}",
          "functional_area": "{!pharos__Trace_Result__c.pharos__Issue__r.pharos__Functional_Area__c}",
          "link": "{!pharos__Trace_Result__c.Link}"
        }
        */
        public final Map<String, String> DEFAULT_WEBHOOK_ACTION = new Map<String, String>{
            'body' => '{\n' +
                '  "event": "trace_result_available",\n' +
                '  "issue_name": "{!' + Schema.SObjectType.Trace_Result__c.getName() + '.' + Schema.SObjectType.Trace_Result__c.fields.Issue__c.getRelationshipName() + '.' + Schema.SObjectType.Issue__c.fields.Name.getName() + '}",\n' +
                '  "issue_summary": "{!' + Schema.SObjectType.Trace_Result__c.getName() + '.' + Schema.SObjectType.Trace_Result__c.fields.Issue__c.getRelationshipName() + '.' + Schema.SObjectType.Issue__c.fields.Summary__c.getName() + '}",\n' +
                '  "category": "{!' + Schema.SObjectType.Trace_Result__c.getName() + '.' + Schema.SObjectType.Trace_Result__c.fields.Issue__c.getRelationshipName() + '.' + Schema.SObjectType.Issue__c.fields.Category__c.getName() + '}",\n' +
                '  "functional_area": "{!' + Schema.SObjectType.Trace_Result__c.getName() + '.' + Schema.SObjectType.Trace_Result__c.fields.Issue__c.getRelationshipName() + '.' + Schema.SObjectType.Issue__c.fields.Functional_Area__c.getName() + '}",\n' +
                '  "link": "{!' + Schema.SObjectType.Trace_Result__c.getName() + '.Link}"\n' +
                '}'
        };
    }
}