main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Action__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <label>Action Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/EventAction__c/EventAction__c.object-meta.xml
<CustomObject>
    <label>Event Action</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>Event Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/EventAction__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Event Actions</relationshipLabel>
    <relationshipName>EventActions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/NotificationServiceEventActionImplTest.cls
@isTest
public class NotificationServiceEventActionImplTest {

    @isTest
    static void testGetSObjectType() {
        NotificationServiceEventActionImpl service = new NotificationServiceEventActionImpl();
        System.assertEquals(EventAction__c.SObjectType, service.getRecordSObjectType(), 'Should return EventAction__c SObjectType');
    }

    @isTest
    static void testGetServiceType() {
        NotificationServiceEventActionImpl service = new NotificationServiceEventActionImpl();
        System.assertEquals(NotificationService.NOTIFICATION_SERVICE_TYPE.EVENT_ACTION, service.getServiceType(), 'Should return EVENT_ACTION service type');
    }

    @isTest
    static void testIsPermissionEnabled() {
        NotificationServiceEventActionImpl service = new NotificationServiceEventActionImpl();
        System.assertEquals(true, service.isPermissionEnabled(), 'Permission should be enabled by default');
    }

    @isTest
    static void testFieldNameMethods() {
        NotificationServiceEventActionImpl service = new NotificationServiceEventActionImpl();
        System.assertEquals('Executable_Rules__c', service.getExecutableRulesFieldName(), 'Should return correct executable rules field name');
        System.assertEquals('Notification_Integration_Status__c', service.getNotificationStatusFieldName(), 'Should return correct notification status field name');
        System.assertEquals('Jira_Integration_Status__c', service.getTicketingStatusFieldName(), 'Should return correct ticketing status field name');
    }

    @isTest
    static void testGetActionIterationsNonAutoChart() {
        NotificationServiceEventActionImpl service = new NotificationServiceEventActionImpl();

        EventAction__c evt = new EventAction__c();
        Action__c act = new Action__c(Subject__c = 'Subject without charts', Body__c = 'Plain body');
        evt.Action__r = act; // unsaved related action is enough for method logic
        evt.Action__c = 'a01xx0000000001AAA';
        evt.Action_Type__c = Constants.ACTION_SOBJECT.ACTION_TYPE_EMAIL_NOTIFICATION;

        List<NotificationService.ActionIteration> iters = service.getActionIterations(evt);
        System.assertEquals(1, iters.size(), 'Should produce one standard iteration');
        System.assertEquals(2, iters[0].totalIterations, 'Total iterations should account for precalc + 1');
        System.assertEquals(Constants.ACTION_SOBJECT.ACTION_TYPE_EMAIL_NOTIFICATION, iters[0].actionType, 'Action type should propagate');
        System.assertEquals(evt.Action__c, iters[0].actionId, 'Action id should propagate');
    }

}