main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Action__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <label>Action Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>JIRA Epic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Action__c/fields/EmailBody__c.field-meta.xml
<CustomField>
    <fullName>EmailBody__c</fullName>
    <label>Email Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Action__c/fields/EmailCC__c.field-meta.xml
<CustomField>
    <fullName>EmailCC__c</fullName>
    <label>Email CC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/EmailTo__c.field-meta.xml
<CustomField>
    <fullName>EmailTo__c</fullName>
    <label>Email To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/JIRAComponents__c.field-meta.xml
<CustomField>
    <fullName>JIRAComponents__c</fullName>
    <label>JIRA Components</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/JIRAEpic__c.field-meta.xml
<CustomField>
    <fullName>JIRAEpic__c</fullName>
    <label>JIRA Epic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/JIRAIssueType__c.field-meta.xml
<CustomField>
    <fullName>JIRAIssueType__c</fullName>
    <label>JIRA Issue Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/JIRALabels__c.field-meta.xml
<CustomField>
    <fullName>JIRALabels__c</fullName>
    <label>JIRA Labels</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/JIRAPriority__c.field-meta.xml
<CustomField>
    <fullName>JIRAPriority__c</fullName>
    <label>JIRA Priority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/JIRAProject__c.field-meta.xml
<CustomField>
    <fullName>JIRAProject__c</fullName>
    <label>JIRA Project</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/SlackChannels__c.field-meta.xml
<CustomField>
    <fullName>SlackChannels__c</fullName>
    <label>Slack Channels</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Action__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Type</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Connected_Org__c/Connected_Org__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Connected Org</label>
</CustomObject>

main/default/objects/Connected_Org__c/fields/Data_Direction__c.field-meta.xml
<CustomField>
    <fullName>Data_Direction__c</fullName>
    <label>Data Direction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/RecordCount__c.field-meta.xml
<CustomField>
    <fullName>RecordCount__c</fullName>
    <label>Number of Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Event__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Inbound_Email__c/Inbound_Email__c.object-meta.xml
<CustomObject>
    <label>Inbound Email</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Inbound_Email__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Inbound_Email__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Inbound Emails</relationshipLabel>
    <relationshipName>Inbound_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Inbound_Email__c/fields/Plain_Text__c.field-meta.xml
<CustomField>
    <fullName>Plain_Text__c</fullName>
    <label>Plain Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Functional Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Pharos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Broadcast_Status__c.field-meta.xml
<CustomField>
    <fullName>Broadcast_Status__c</fullName>
    <label>Broadcast Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Email-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Lead</fullName>
            </value>
            <value>
                <fullName>Pharos Error</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>OmniStudio</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Created At</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Hash_1__c.field-meta.xml
<CustomField>
    <fullName>Hash_1__c</fullName>
    <label>Hash 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <label>Error</label>
</RecordType>

main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <label>Rule</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Rule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Rule__c/fields/ComparisonOperator__c.field-meta.xml
<CustomField>
    <fullName>ComparisonOperator__c</fullName>
    <label>Comparison Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ComparisonOperator</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Rule__c/fields/EventTimeInterval__c.field-meta.xml
<CustomField>
    <fullName>EventTimeInterval__c</fullName>
    <label>Event Time Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Archival</fullName>
            </value>
            <value>
                <fullName>JIRA Update</fullName>
            </value>
            <value>
                <fullName>Notification</fullName>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
            <value>
                <fullName>Limits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/RuleAction__c/RuleAction__c.object-meta.xml
<CustomObject>
    <label>Rule Action</label>
    <nameField>
        <displayFormat>RA-{0000000}</displayFormat>
        <label>Rule Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/RuleAction__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Rule Actions</relationshipLabel>
    <relationshipName>RuleActions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/RuleAction__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Actions</relationshipLabel>
    <relationshipName>RuleActions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/RuleFilter__c/RuleFilter__c.object-meta.xml
<CustomObject>
    <label>Rule Filter</label>
    <nameField>
        <displayFormat>RF-{0000000}</displayFormat>
        <label>Rule Filter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/RuleFilter__c/fields/Comparison_Type__c.field-meta.xml
<CustomField>
    <fullName>Comparison_Type__c</fullName>
    <label>Comparison Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Value</fullName>
            </value>
            <value>
                <fullName>Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/RuleFilter__c/fields/ComparisonOperator__c.field-meta.xml
<CustomField>
    <fullName>ComparisonOperator__c</fullName>
    <label>Comparison Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equal</fullName>
            </value>
            <value>
                <fullName>Not equal</fullName>
            </value>
            <value>
                <fullName>Greater than</fullName>
            </value>
            <value>
                <fullName>Greater or equal</fullName>
            </value>
            <value>
                <fullName>Less than</fullName>
            </value>
            <value>
                <fullName>Less or equal</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Doesn&apos;t Contain</fullName>
            </value>
            <value>
                <fullName>Includes</fullName>
            </value>
            <value>
                <fullName>Excludes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/RuleFilter__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/RuleFilter__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Filters</relationshipLabel>
    <relationshipName>RuleFilters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/LogServiceSchedulerTest.cls
@IsTest
private class LogServiceSchedulerTest {

	@TestSetup
	private static void testSetup() {
		ConfigUtil.SETTINGS.Service_Scheduler_Enabled__c = true;
		ConfigUtil.SETTINGS.Archival_Enabled__c = true;
		upsert ConfigUtil.SETTINGS;
	}

	@IsTest
	private static void test_LogServiceScheduler() {
		LogServiceScheduler.rescheduleCronTriggers();

		System.assertEquals(1, [SELECT COUNT() FROM CronTrigger WHERE CronJobDetail.Name = :ConfigUtil.PHAROS_LOG_SERVICE_SCHEDULER_MODE_1_NAME]);
		System.assertEquals(1, [SELECT COUNT() FROM CronTrigger WHERE CronJobDetail.Name = :ConfigUtil.PHAROS_LOG_SERVICE_SCHEDULER_MODE_2_NAME]);
	}

	@IsTest
	private static void test_startJobsMode1() {
		Test.startTest();
		test_startJobs(LogServiceScheduler.SCHEDULER_MODE.SCHEDULER_MODE_1);
		System.assertEquals(DatabaseUtils.startJobs, new Set<String>{
				'LogServiceBatch',
				'ManageTokensBatch',
				'EventLogProcessingBatch',
				'RetentionBatch',
				'MonitoringBatch',
				'JiraNotificationBatch',
				'IssueNotificationBatch',
				'TraceResultNotificationBatch',
				'BroadcastBatch',
				'JobBatch',
				'GitHubCommitBatch',
				'IssueTrackerBatch',
				'JiraSyncBatch',
				'TraceService'
		});
		Test.stopTest();
	}

	@IsTest
	private static void test_startJobsMode2() {
		Test.startTest();
		test_startJobs(LogServiceScheduler.SCHEDULER_MODE.SCHEDULER_MODE_2);
		System.assertEquals(DatabaseUtils.startJobs, new Set<String>{
				'ManageTokensBatch',
				'LogPostProcessingBatch',
				'ErrorEmailReportBatch',
				'JiraResolutionBatch',
				'MetricsBatch',
				'IssueAverageFrequencyBatch',
				'TraceService',
				'BulkAPIJobBatchScheduler',
				'TraceBatch'
		});
		Test.stopTest();
	}

	private static void test_startJobs(LogServiceScheduler.SCHEDULER_MODE schedulerMode) {
		DatabaseUtils.TEST_MODE = true;
		LogServiceScheduler logServiceScheduler = new LogServiceScheduler(schedulerMode);
		logServiceScheduler.execute(null);
	}

	@IsTest
	private static void test_queueJobsMode1() {
		test_queueJobs(LogServiceScheduler.SCHEDULER_MODE.SCHEDULER_MODE_1);

		System.assertEquals(4, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL]);
		System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL AND ApexClass.Name = 'LogServiceBatch']);
		System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL AND ApexClass.Name = 'ManageTokensBatch']);
		System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL AND ApexClass.Name = 'RetentionBatch']);
		System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL AND ApexClass.Name = 'ArchivalBatch']);
		System.assertEquals(3, [SELECT COUNT() FROM Log__c WHERE Category__c = 'TestCategory']);
	}

	@IsTest
	private static void test_queueJobsMode2() {
		test_queueJobs(LogServiceScheduler.SCHEDULER_MODE.SCHEDULER_MODE_2);

		System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL]);
		System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL AND ApexClass.Name = 'ManageTokensBatch']);
	}

	private static void test_queueJobs(LogServiceScheduler.SCHEDULER_MODE schedulerMode) {
		initData_LogServiceBatch();
		initData_ManageTokensBatch();
		initData_RetentionBatch();
		TestDataFactory.enableMaxArchivalRules();

		System.assertEquals(4, [SELECT COUNT() FROM Log__c WHERE Category__c = 'TestCategory']);

		Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String, HttpCalloutMock>();
		endpoint2TestResp.put('https://test_Instance_Url' + ConfigUtil.SF_OAUTH_TOKEN_ENDPOINT, refreshTokenMock());
		endpoint2TestResp.put(JiraService.JIRA_CLOUD_OAUTH_ENDPOINT, createJiraRefreshRequestMock());
		HttpCalloutMock multiCalloutMock = new TestDataFactory.MultiRequestMock(endpoint2TestResp);
		Test.setMock(HttpCalloutMock.class, multiCalloutMock);

		Test.startTest();
		LogServiceScheduler logServiceScheduler = new LogServiceScheduler(schedulerMode);
		logServiceScheduler.execute(null);
		Test.stopTest();
	}

	// LogServiceBatch

	private static void initData_LogServiceBatch() {
		TestDataFactory.createConnectedOrgSettings();
		TestDataFactory.createConnectedOrg();
	}

	private static TestDataFactory.SingleRequestMock refreshTokenMock() {
		ConnectedOrgService.AuthTokenResponse authTokenResponse = new ConnectedOrgService.AuthTokenResponse();
		authTokenResponse.access_token = 'test_new_Access_Token';
		TestDataFactory.SingleRequestMock singleRequestMock = new TestDataFactory.SingleRequestMock(
				200,
				'OK',
				JSON.serialize(authTokenResponse)
		);
		return singleRequestMock;
	}

	// ManageTokensBatch

	private static final String TEST_JIRA_API_URL = 'https://somejiraapiurl.com';
	private static final String TEST_JIRA_BASE_URL = 'https://somejiraapiurl.com/jirasiteid';
	private static final String TEST_JIRA_API_ACCESS_TOKEN_BEFORE = 'sometoken1';
	private static final String TEST_JIRA_API_REFRESH_TOKEN_BEFORE = 'somerefreshtoken1';
	private static final String TEST_JIRA_API_ACCESS_TOKEN_AFTER = 'sometoken2';
	private static final String TEST_JIRA_API_REFRESH_TOKEN_AFTER = 'somerefreshtoken2';
	private static final String TEST_JIRA_API_USERNAME = JiraService.JIRA_CLOUD_OAUTH_USERNAME;

	private static void initData_ManageTokensBatch() {
		ConfigUtil.JIRA_SETTINGS.Jira_API_Url__c = TEST_JIRA_API_URL;
		ConfigUtil.JIRA_SETTINGS.Jira_Base_Url__c = TEST_JIRA_BASE_URL;
		ConfigUtil.JIRA_SETTINGS.Jira_Username__c = TEST_JIRA_API_USERNAME;
		upsert ConfigUtil.JIRA_SETTINGS;
		JiraService.putApiTokenToSettings(TEST_JIRA_API_ACCESS_TOKEN_BEFORE, true, null);
		JiraService.putApiRefreshTokenToSettings(TEST_JIRA_API_REFRESH_TOKEN_BEFORE, true, null);
	}

	private static TestDataFactory.SingleRequestMock createJiraRefreshRequestMock() {
		ConnectedOrgService.AuthTokenResponse response = new ConnectedOrgService.AuthTokenResponse();
		response.refresh_token = TEST_JIRA_API_REFRESH_TOKEN_AFTER;
		response.access_token = TEST_JIRA_API_ACCESS_TOKEN_AFTER;
		TestDataFactory.SingleRequestMock jiraRefreshRequestMock = new TestDataFactory.SingleRequestMock(
				200,
				'OK',
				JSON.serialize(response)
		);
		return jiraRefreshRequestMock;
	}

	// RetentionBatch

	private static void initData_RetentionBatch() {
		Rule__c mr1 = new Rule__c();
		mr1.Active__c = true;
		mr1.Type__c = MonitoringUtil.RULE_TYPE_ARCHIVAL;
		mr1.EventTimeInterval__c = 1*60;
		insert mr1;

		Id recordtypeId = Schema.SObjectType.Action__c.getRecordTypeInfosByName().get(MonitoringUtil.RULE_TYPE_ARCHIVAL).getRecordTypeId();

		Action__c rn1 = new Action__c();
		rn1.RecordTypeId = recordtypeId;
		rn1.Description__c = 'test';
		rn1.Subject__c = 'test';
		rn1.Body__c = 'test';
		rn1.EmailBody__c = 'test';
		rn1.SlackChannels__c = 'test';
		rn1.EmailTo__c = 'test@test.cc';
		rn1.EmailCC__c = 'test2@test.cc';
		rn1.JIRALabels__c = 'test';
		rn1.JIRAComponents__c = 'test';
		rn1.JIRAEpic__c = 'test';
		rn1.JIRAPriority__c = 'test';
		rn1.JIRAProject__c = 'test';
		rn1.JIRAIssueType__c = 'test';
		rn1.Action_Type__c = MonitoringUtil.ACTION_TYPE_REMOVAL;
		insert rn1;

		RuleAction__c en1 = new RuleAction__c();
		en1.Action__c = rn1.Id;
		en1.Rule__c = mr1.Id;
		insert en1;

		RuleFilter__c rf1 = new RuleFilter__c();
		rf1.Index__c = 1;
		rf1.Rule__c = mr1.Id;
		rf1.ComparisonOperator__c = 'Greater than';
		rf1.FieldName__c = 'Created_At__c';
		rf1.Value__c = '13600';
		rf1.Comparison_Type__c = 'Value';
		insert rf1;

		Log__c log = new Log__c();
		log.Category__c = 'TestCategory';
		log.Type__c = 'TestType' ;
		log.Area__c = 'Apex';
		log.Details__c = 'pass pass pass pass pass pass pass';

		Datetime dtnow = Datetime.now();
		Datetime currentTime = Datetime.newInstance(dtnow.year(), dtnow.month(), dtnow.day(), dtnow.hour(), dtnow.minute(), dtnow.second());
		Datetime time_2h_ago = currentTime.addHours(-2);
		Datetime time_3h_ago = currentTime.addHours(-3);
		Datetime time_6h_ago = currentTime.addHours(-6);

		Log__c log_2h_ago = log.clone(); log_2h_ago.Created_At__c = time_2h_ago;
		Log__c log_3h_ago = log.clone(); log_3h_ago.Created_At__c = time_3h_ago;
		Log__c log_6h_ago = log.clone(); log_6h_ago.Created_At__c = time_6h_ago;
		List<Log__c> allLogs = new List<Log__c>{log, log_2h_ago, log_3h_ago, log_6h_ago};
		insert allLogs;

		List<Inbound_Email__c> logEmails = new List<Inbound_Email__c>();
		for (Log__c logIterator : allLogs) {
			logEmails.add(createInboundEmail(logIterator.Id));
		}
		insert logEmails;

		Event__c lastEvent = new Event__c();
		lastEvent.RecordCount__c = 1;
		lastEvent.Rule__c = mr1.Id;
		insert lastEvent;
		Test.setCreatedDate(lastEvent.Id, currentTime.addMinutes(-2*60));

	}

	public static final String INBOUND_EMAIL_SUBJECT = 'Subject';
	public static final String INBOUND_EMAIL_PLAIN_TEXT = 'Please review error';
	public static final String INBOUND_EMAIL_FROM = 'erroruser@somedomain.com';

	private static Inbound_Email__c createInboundEmail(Id logId) {
		Inbound_Email__c inboundEmail = new Inbound_Email__c();
		inboundEmail.Subject__c = INBOUND_EMAIL_SUBJECT;
		inboundEmail.Plain_Text__c = INBOUND_EMAIL_PLAIN_TEXT;
		inboundEmail.From__c = INBOUND_EMAIL_FROM;
		return inboundEmail;
	}

	@IsTest
	private static void test_scopeJobsMode1_BroadcastBatch() {
		initData_LogServiceBatch();

		Connected_Org__c corg = ConnectedOrgService.getConnectedOrgById(UserInfo.getOrganizationId().left(15));
		corg.Data_Direction__c = 'sendTo';
		update corg;

		Log__c log = new Log__c();
		log.Hash_1__c = 'hash1';
		log.Category__c = 'Other';
		log.Type__c = 'Custom';
		log.Broadcast_Status__c = BroadcastService.BROADCAST_STATUS_NEEDED;
		log.Organization_Id__c = UserInfo.getOrganizationId().left(15);
		insert log;

		String query = new QBuilder(Log__c.SObjectType)
				.selectFields(new Set<String>{'FIELDS(ALL)'})
				.add(QBuilder.condition(Log__c.Broadcast_Status__c.getDescribe().getName()).equalsTo(BroadcastService.BROADCAST_STATUS_NEEDED))
				.add(QBuilder.condition(Log__c.Originated_From__c.getDescribe().getName()).isNull())
				.addLimit(BroadcastService.queryLimit)
				.build();
		Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String, HttpCalloutMock>();
		endpoint2TestResp.put('https://test_Instance_Url' + ConfigUtil.SF_OAUTH_TOKEN_ENDPOINT, refreshTokenMock());
		endpoint2TestResp.put(Url.getOrgDomainUrl().toExternalForm() + ConfigUtil.QUERY_REST_API_PATH + EncodingUtil.urlEncode(query, 'UTF-8'), new TestDataFactory.SingleRequestMock(
				200,
				'OK',
				'{"records":[{"attributes":{"type":"Log__c"},"Id":"' + log.Id + '","' + Log__c.Type__c.getDescribe().getName() + '":"Test"}]}'
		));
		endpoint2TestResp.put('https://test_Instance_Url' + ConfigUtil.PHAROS_REST_SERVICE_ENDPOINT + '?' + ConfigUtil.PARAMS_TYPE + '=' + ConfigUtil.TYPE_BROADCAST, sendLogMock());
		HttpCalloutMock multiCalloutMock = new TestDataFactory.MultiRequestMock(endpoint2TestResp);
		Test.setMock(HttpCalloutMock.class, multiCalloutMock);

		test_scopeJobs(LogServiceScheduler.SCHEDULER_MODE.SCHEDULER_MODE_1);

		System.assertEquals(2, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL]);
		System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL AND ApexClass.Name = 'LogServiceBatch']);
		System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL AND ApexClass.Name = 'BroadcastBatch']);
	}

	private static TestDataFactory.SingleRequestMock sendLogMock() {
		TestDataFactory.SingleRequestMock singleRequestMock = new TestDataFactory.SingleRequestMock(
				200,
				'OK',
				'Done'
		);
		return singleRequestMock;
	}

	@IsTest
	private static void test_scopeJobsMode2_LogPostProcessingBatch() {
		Log__c log = new Log__c();
		log.Hash_1__c = 'hash1';
		log.Category__c = 'Other';
		log.Type__c = 'Custom';
		log.Post_Processing_Settings__c = '["UI"]';
		log.Post_Processing_Status__c = LogPostProcessingService.POST_PROCESSING_STATUS_NEEDED;
		log.Organization_Id__c = UserInfo.getOrganizationId().left(15);
		insert log;

		test_scopeJobs(LogServiceScheduler.SCHEDULER_MODE.SCHEDULER_MODE_2);

		System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL]);
		System.assertEquals(1, [SELECT COUNT() FROM AsyncApexJob WHERE ParentJobId = NULL AND ApexClass.Name = 'LogPostProcessingBatch']);
	}

	private static void test_scopeJobs(LogServiceScheduler.SCHEDULER_MODE schedulerMode) {
		Test.startTest();
		LogServiceScheduler logServiceScheduler = new LogServiceScheduler(schedulerMode);
		logServiceScheduler.execute(null);
		Test.stopTest();
	}

}