main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Email-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Lead</fullName>
            </value>
            <value>
                <fullName>Pharos Error</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>OmniStudio</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Flow_Link__c.field-meta.xml
<CustomField>
    <fullName>Flow_Link__c</fullName>
    <formula>HYPERLINK(Organization_Url__c&amp;&apos;/builder_platform_interaction/flowBuilder.app?isFromAloha=true&amp;flowId=&apos;&amp;Flow_Version_Id__c, Flow_API_Name__c,&quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flow Link</label>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <label>Stacktrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Stacktrace_Parse_Result__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace_Parse_Result__c</fullName>
    <label>Stacktrace Parse Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/classes/StacktraceViewerWrapperController.cls
public with sharing class StacktraceViewerWrapperController {

    public Log__c log { get; set; }
	public String packageNamespace { get {return ConfigUtil.getNameSpacePrefix();} set; }
	public Boolean isDev { get; set; }
	public Boolean isBlurMode { get; set; }
	public String stacktraceCvId { get; set; }
	public String stacktraceParseResultCvId { get; set; }

	public StacktraceViewerWrapperController(ApexPages.StandardController stdController) {
		this.log = [
			SELECT Id, Name, Flow_Link__c, Stacktrace__c, Stacktrace_Parse_Result__c, Type__c, Category__c,
			(SELECT Id, ContentDocument.LatestPublishedVersion.Id, ContentDocument.LatestPublishedVersion.PathOnClient FROM ContentDocumentLinks)
			FROM Log__c
			WHERE Id = :stdController.getId()
		];
		for(ContentDocumentLink cdl : log?.ContentDocumentLinks) {
			if(cdl?.ContentDocument?.LatestPublishedVersion?.PathOnClient == ErrorEmailHandler.STACK_TRACE_CV_NAME) {
				this.stacktraceCvId = cdl.ContentDocument.LatestPublishedVersion.Id;
			}
			if(cdl?.ContentDocument?.LatestPublishedVersion?.PathOnClient == ErrorEmailHandler.STACK_TRACE_PARSE_RESULT_CV_NAME) {
				this.stacktraceParseResultCvId = cdl.ContentDocument.LatestPublishedVersion.Id;
			}
		}

		isDev = ConfigUtil.initializeDevelopmentMode(ApexPages.currentPage());
		isBlurMode = !BlurModeService.isAvailableDebugView(this.log.Id);
	}
}