main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Hash_1__c.field-meta.xml
<CustomField>
    <fullName>Hash_1__c</fullName>
    <label>Hash 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Hash_2__c.field-meta.xml
<CustomField>
    <fullName>Hash_2__c</fullName>
    <label>Hash 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Hash_3__c.field-meta.xml
<CustomField>
    <fullName>Hash_3__c</fullName>
    <label>Hash 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Id__c</fullName>
    <label>Organization Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <label>Error</label>
</RecordType>

main/default/objects/Log_Index__c/Log_Index__c.object-meta.xml
<CustomObject>
    <label>Log Index</label>
    <nameField>
        <displayFormat>LI-{000000}</displayFormat>
        <label>Log Index Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Index</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log_Index__c/fields/Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Id__c</fullName>
    <label>Organization Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Log_Index__c/fields/Reported_to_Pharos_On__c.field-meta.xml
<CustomField>
    <fullName>Reported_to_Pharos_On__c</fullName>
    <label>Reported to Pharos On</label>
    <type>DateTime</type>
</CustomField>

main/default/classes/PharosErrorReportActionControllerTest.cls
@IsTest
public with sharing class PharosErrorReportActionControllerTest {

    @TestSetup
    static void makeData() {
        String orgID = UserInfo.getOrganizationId().left(15);
        Log__c log = new Log__c();
        log.Hash_1__c = 'hash1';
        log.Hash_2__c = 'hash2';
        log.Hash_3__c = 'hash3';
        log.Organization_Id__c = orgID;

        insert log;

        Log_Index__c logIndex = getLogIndex();
        ErrorEmailReportBatch.setReported(new List<Log_Index__c>{ logIndex }, Logger.getInstance());
    }

    @IsTest
    static void test_isAvailableSingleEmail() {
        Boolean result;
        Test.startTest();
            result = PharosErrorReportActionController.isAvailableSingleEmail();
        Test.stopTest();

        Assert.isTrue(result, 'Single email should be available');
    }

    @IsTest
    static void test_getReportedInfo() {
        Log__c log = getLog();
        Log_Index__c logIndex = getLogIndex();

        Map<String, Object> result;
        Test.startTest();
            result = PharosErrorReportActionController.getReportedInfo(log.Id);
        Test.stopTest();

        Assert.isTrue(result != null && !result.isEmpty(), 'Reported info should not be null or empty');
        
        Datetime reportedToPharosOn = (Datetime) result.get(PharosErrorReportActionController.KEY_REPORTED_TO_PHAROS_ON);
        String createdByName = (String) result.get(PharosErrorReportActionController.KEY_CREATED_BY_NAME);
        
        Assert.isTrue(reportedToPharosOn != null, 'The ' + PharosErrorReportActionController.KEY_REPORTED_TO_PHAROS_ON + ' should not be null');
        Assert.areEqual(logIndex.Reported_to_Pharos_On__c, reportedToPharosOn, 'The ' + PharosErrorReportActionController.KEY_REPORTED_TO_PHAROS_ON + ' does not match');

        Assert.isTrue(String.isNotBlank(createdByName), 'The ' + PharosErrorReportActionController.KEY_CREATED_BY_NAME + ' should not be null or empty');
        Assert.areEqual(logIndex.CreatedBy.Name, createdByName, 'The ' + PharosErrorReportActionController.KEY_CREATED_BY_NAME + ' does not match');
    }
    
    @IsTest
    static void test_getErrorEmailAddress() {
        String result;
        Test.startTest();
            result = PharosErrorReportActionController.getErrorEmailAddress();
        Test.stopTest();

        Assert.isTrue(String.isNotBlank(result), 'The email should not be blank');
        Assert.areEqual(ErrorEmailReportBatch.PHAROS_ERROR_EMAIL_ADDRESS, result, 'Error email does not match');
    }

    @IsTest
    static void test_getTotalOccurrences_WithExistingLog() {
        Log__c log = getLog();

        Integer result;
        Test.startTest();
            result = PharosErrorReportActionController.getTotalOccurrences(log.Id);
        Test.stopTest();

        Assert.areEqual(1, result, 'Total Occurrences do not match');
    }

    @IsTest
    static void test_getTotalOccurrences_WithNotExistingLog() {
        Integer result;
        Test.startTest();
            result = PharosErrorReportActionController.getTotalOccurrences(TestDataFactory.getFakeIds(Log__c.SObjectType, 1).get(0));
        Test.stopTest();

        Assert.areEqual(0, result, 'Total Occurrences do not match');
    }

    @IsTest
    static void test_sendPharosErrorReport() {
        Log__c log = getLog();
        Log_Index__c logIndexBefore = getLogIndex();

        Test.startTest();
            PharosErrorReportActionController.sendPharosErrorReport(log.Id, 'test_summary', 'test_details', 'test_comments');
        Test.stopTest();

        Log_Index__c logIndexAfter = getLogIndex();

        Assert.areNotEqual(null, logIndexAfter, 'Log index should still exist after method execution');
        
        Log__c originalLog = [SELECT Id, Summary__c, Details__c FROM Log__c WHERE Id = :log.Id];
        Assert.areNotEqual(null, originalLog, 'Original log should still exist');
    }

    private static Log__c getLog() {
        return [SELECT Id FROM Log__c];
    }

    private static Log_Index__c getLogIndex() {
        return [SELECT Reported_to_Pharos_On__c, CreatedBy.Name FROM Log_Index__c];
    }
}