main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Apex_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Name__c</fullName>
    <label>Operation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Functional Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Pharos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Email-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Lead</fullName>
            </value>
            <value>
                <fullName>Pharos Error</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>OmniStudio</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Created_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Created_Timestamp__c</fullName>
    <label>Created Timestamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Do_Not_Create_Issue__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Create_Issue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Create Issue</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Log__c/fields/Hash_1__c.field-meta.xml
<CustomField>
    <fullName>Hash_1__c</fullName>
    <label>Hash 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Id__c</fullName>
    <label>Organization Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Post_Processing_Settings__c.field-meta.xml
<CustomField>
    <fullName>Post_Processing_Settings__c</fullName>
    <label>Post Processing Settings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Related_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Id__c</fullName>
    <label>Related Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Related_Objects__c.field-meta.xml
<CustomField>
    <fullName>Related_Objects__c</fullName>
    <label>Related Objects</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Request_Id_External__c.field-meta.xml
<CustomField>
    <fullName>Request_Id_External__c</fullName>
    <externalId>true</externalId>
    <label>Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <label>Stacktrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Transaction_Id_External__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id_External__c</fullName>
    <externalId>true</externalId>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/LogBuilder.cls
global virtual with sharing class LogBuilder {

	private final Log__c log;

	private static final Integer MAX_LENGTH_TEXT_FIELD = 255;

	global static LogBuilder getInstance() {
		return new LogBuilder();
	}

	global LogBuilder() {
		log = (Log__c)PermissionsUtil.newSObject(Schema.SObjectType.Log__c);
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Created_Timestamp__c, Double.valueOf(System.now().getTime()));
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Request_Id_External__c, System.Request.getCurrent().getRequestId());
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Do_Not_Create_Issue__c, true);
	}

	global LogBuilder type(String value) {
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Type__c, value);
		return this;
	}

	global LogBuilder summary(String value) {
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Summary__c, String.isEmpty(value) ? null : value.abbreviate(MAX_LENGTH_TEXT_FIELD));
		return this;
	}

	global LogBuilder details(String value) {
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Details__c, value);
		return this;
	}

	global LogBuilder category(String value) {
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Category__c, value);
		return this;
	}

	global LogBuilder stackTrace(String value) {
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Stacktrace__c, value);
		return this;
	}

	global LogBuilder area(String value) {
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Area__c, value);
		return this;
	}

	global LogBuilder postProcessing(String settingsJSON) {
		Map<String, Boolean> settings;
		try {
			settings = (Map<String, Boolean>)JSON.deserialize(settingsJSON, Map<String, Boolean>.class);
		} catch (JSONException e) {
			// catch JSON deserialize issue
		}
		Set<String> setSettings = new Set<String>();
		if (settings != null) {
			for (String key : settings.keySet()) {
				if (settings.get(key) && LogPostProcessingService.SETTINGS_ABBREVIATION.containsKey(key)) {
					setSettings.add(LogPostProcessingService.SETTINGS_ABBREVIATION.get(key));
				}
			}
		}
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Post_Processing_Settings__c, JSON.serialize(setSettings));
		return this;
	}

	global LogBuilder transactionId(String value) {
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Transaction_Id_External__c, value);
		return this;
	}

	global LogBuilder createIssue() {
		PermissionsUtil.putSObjectField(this.log, Schema.SObjectType.Log__c.fields.Do_Not_Create_Issue__c, false);
		return this;
	}

	global LogBuilder attribute(String field, Object value) {
		if (value != null) {
			try {
				if (field.equals(Schema.SObjectType.Log__c.fields.Related_Id__c.getName())) {
					Id relatedId = (Id) value;
				}
				if (field.equals(Schema.SObjectType.Log__c.fields.User_Id__c.getName())) {
					Id userId = (Id) value;
					if (userId.getSObjectType() != Constants.USER_SOBJECT.SOBJECT_TYPE) {
						value = null;

						Logger.getInstance().add(
							getInstance()
								.category(Logger.CATEGORY_PHAROS_ERROR)
								.summary('The ' + Schema.SObjectType.Log__c.fields.User_Id__c.getName() + 'field should contain the record id of the User object')
								.area(Logger.AREA_PHAROS_ERROR)
								.type(Logger.AREA_PHAROS_ERROR)
								.details('The ' + Schema.SObjectType.Log__c.fields.User_Id__c.getName() + 'field should contain the record id of the User object')
								.attribute(Schema.SObjectType.Log__c.fields.Organization_Id__c.getName(), UserInfo.getOrganizationId().left(15))
								.attribute(Schema.SObjectType.Log__c.fields.Apex_Name__c.getName(), LogBuilder.class.getName() + ':' + 'attribute')
								.build()
						);
					}
				}
				if (field.equals(Schema.SObjectType.Log__c.fields.Related_Objects__c.getName())) {
					Set<Id> recordIds = (Set<Id>) JSON.deserialize((String) value, Set<Id>.class);
				}
			} catch (Exception ex) {
				value = null;
				Logger.getInstance().addInternalError(ex, LogBuilder.class.getName(), 'attribute');
			}
		}

		PermissionsUtil.putSObjectField(this.log, field, value);
		return this;
	}

	global virtual LogBuilder tracePoint() {
		LogService.calculateHashes(this.log);
		return this;
	}

	global virtual String getTraceId() {
		return this.log?.Hash_1__c;
	}

	global Log__c build() {
		return log;
	}

}