main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>ISS-{00000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Issue__c/fields/First_Occurred_On__c.field-meta.xml
<CustomField>
    <fullName>First_Occurred_On__c</fullName>
    <label>First Occurred On</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Issue__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Issue__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <label>Organization Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Created At</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Do_Not_Create_Issue__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Create_Issue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Create Issue</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Log__c/fields/First_Occurred_On__c.field-meta.xml
<CustomField>
    <fullName>First_Occurred_On__c</fullName>
    <label>First Occurred On</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Log__c/fields/Hash_1__c.field-meta.xml
<CustomField>
    <fullName>Hash_1__c</fullName>
    <label>Hash 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Issue__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Log__c/fields/Issue_Tracker_Status__c.field-meta.xml
<CustomField>
    <fullName>Issue_Tracker_Status__c</fullName>
    <label>Issue Tracker Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Post_Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Post_Processing_Status__c</fullName>
    <label>Post Processing Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/classes/IssueTrackerBatch.cls
public with sharing class IssueTrackerBatch extends DatabaseUtils.PharosBatchImpl implements Database.Batchable<SObject>, Database.Stateful, Database.RaisesPlatformEvents {

	public Map<String, List<Log__c>> mapLogsByHash;
	public Map<String, Issue__c> mapIssuesByHash;

	private static final Integer QUERY_LIMIT = 1000;

	private static IssueTrackerBatch instance = null;

	public static IssueTrackerBatch getInstance() {
		if (instance == null) {
			instance = new IssueTrackerBatch(Logger.getInstance());
		}
		return instance;
	}

	private IssueTrackerBatch(Logger logger) {
		super(logger);
		BATCH_SCOPE = QUERY_LIMIT;
	}

	public override void startBatch() {
		DatabaseUtils.executeBatchWithLimitCheck('IssueTrackerBatch', this);
	}

	public override Boolean initialValidation() {
		return PermissionsUtil.IssueTrackingEnabled;
	}

	public override Integer getIterationsCount() {
		if (LimitsService.getMaxIssues() == null || BlurModeService.AVAILABLE_ISSUES_COUNT > 0) {
			return [
				SELECT COUNT()
				FROM Log__c	
				WHERE Issue__c = NULL 
					AND Hash_1__c != NULL 
					AND Do_Not_Create_Issue__c = FALSE 
					AND Post_Processing_Status__c = :IssueService.POST_PROCESSING_STATUS_COMPLETED
					AND Issue_Tracker_Status__c != :IssueService.LOG_ISSUE_TRACKER_STATUS_FAILED
				LIMIT :QUERY_LIMIT
			];
		}
		if (LimitsService.getMaxIssues() != null && BlurModeService.AVAILABLE_ISSUES_COUNT <= 0 && BlurModeService.AVAILABLE_ISSUE_KEYS != null && !BlurModeService.AVAILABLE_ISSUE_KEYS.isEmpty()) {
			return [
				SELECT COUNT()
				FROM Log__c
				WHERE Issue__c = NULL 
					AND Hash_1__c != NULL 
					AND Hash_1__c IN :BlurModeService.AVAILABLE_ISSUE_KEYS 
					AND Do_Not_Create_Issue__c = FALSE 
					AND Post_Processing_Status__c = :IssueService.POST_PROCESSING_STATUS_COMPLETED
					AND Issue_Tracker_Status__c != :IssueService.LOG_ISSUE_TRACKER_STATUS_FAILED
				LIMIT :QUERY_LIMIT
			];
		}
		return 0;
	}

	public Database.QueryLocator start(Database.BatchableContext BC) {
		if (LimitsService.getMaxIssues() == null || BlurModeService.AVAILABLE_ISSUES_COUNT > 0) {
			return Database.getQueryLocator([
					SELECT Id, Summary__c, Details__c, Hash_1__c, Organization_Name__c, First_Occurred_On__c, Created_At__c,
						Issue_Tracker_Status__c	
					FROM Log__c
					WHERE Issue__c = NULL
					AND Hash_1__c != NULL
					AND Do_Not_Create_Issue__c = FALSE
					AND Post_Processing_Status__c = :IssueService.POST_PROCESSING_STATUS_COMPLETED
					AND Issue_Tracker_Status__c != :IssueService.LOG_ISSUE_TRACKER_STATUS_FAILED
					ORDER BY Created_At__c DESC
					LIMIT :QUERY_LIMIT
			]);
		}
		if (LimitsService.getMaxIssues() != null && BlurModeService.AVAILABLE_ISSUES_COUNT <= 0 && BlurModeService.AVAILABLE_ISSUE_KEYS != null && !BlurModeService.AVAILABLE_ISSUE_KEYS.isEmpty()) {
			return Database.getQueryLocator([
					SELECT Id, Summary__c, Details__c, Hash_1__c, Organization_Name__c, First_Occurred_On__c, Created_At__c,
						Issue_Tracker_Status__c
					FROM Log__c
					WHERE Issue__c = NULL
					AND Hash_1__c != NULL
					AND Hash_1__c IN :BlurModeService.AVAILABLE_ISSUE_KEYS
					AND Do_Not_Create_Issue__c = FALSE
					AND Post_Processing_Status__c = :IssueService.POST_PROCESSING_STATUS_COMPLETED
					AND Issue_Tracker_Status__c != :IssueService.LOG_ISSUE_TRACKER_STATUS_FAILED
					ORDER BY Created_At__c DESC
					LIMIT :QUERY_LIMIT
			]);
		}
		return null;
	}

	public void execute(Database.BatchableContext BC, List<Log__c> scope) {
		mapLogsByHash = IssueService.getMapLogsByHash(scope);
		mapIssuesByHash = IssueService.getMapIssuesByHash(mapLogsByHash);
	}

	public void finish(Database.BatchableContext BC) {
		IssueService.issueTracker(mapLogsByHash, mapIssuesByHash, loggerInstance);
		loggerInstance?.flush();
		IssueTrackerBatch.getInstance().startBatch();
	}
}