main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>ISS-{00000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Issue__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Log__r.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

main/default/objects/Issue__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Async_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Async_Job_Id__c</fullName>
    <label>Async Job Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Email-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Lead</fullName>
            </value>
            <value>
                <fullName>Pharos Error</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>OmniStudio</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Created_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Created_Timestamp__c</fullName>
    <label>Created Timestamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Log__c/fields/Flow_Link__c.field-meta.xml
<CustomField>
    <fullName>Flow_Link__c</fullName>
    <formula>HYPERLINK(Organization_Url__c&amp;&apos;/builder_platform_interaction/flowBuilder.app?isFromAloha=true&amp;flowId=&apos;&amp;Flow_Version_Id__c, Flow_API_Name__c,&quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flow Link</label>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Issue__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Log__c/fields/Organization_Url__c.field-meta.xml
<CustomField>
    <fullName>Organization_Url__c</fullName>
    <label>Organization Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Log__c/fields/Stack_trace_parse_result_available__c.field-meta.xml
<CustomField>
    <fullName>Stack_trace_parse_result_available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stack trace parse result available</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <label>Stacktrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Stacktrace_Parse_Result__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace_Parse_Result__c</fullName>
    <label>Stacktrace Parse Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <label>Error</label>
</RecordType>

main/default/classes/StacktraceViewerController.cls
global with sharing class StacktraceViewerController {

	private static final String IS_BLUR_MODE_PARAM_NAME = 'isBlurMode';

	public Boolean isDev { get; set; }
	public Boolean isBlurMode { get; set; }
	public String blurModeUrlParameter { get; set; }
	public Log__c log { get; set; }
	public String stacktraceCvId { get; set; }
	public String stacktraceParseResultCvId { get; set; }
	public String packageNamespace {
		get {
			return ConfigUtil.getNameSpacePrefix();
		}
		set;
	}
	public static String baseUrl {
        get {
	        return System.Url.getOrgDomainUrl().toExternalForm();
        }
        set;
    }

	private static final SObjectType LOG_SOBJECT_TYPE = Log__c.SObjectType;
	private static final SObjectType ISSUE_SOBJECT_TYPE = Issue__c.SObjectType;

	public StacktraceViewerController(ApexPages.StandardController stdController) {
		System.PageReference pageReference = ApexPages.currentPage();
		String recordId = pageReference.getParameters().get('recordId');
		isDev = ConfigUtil.initializeDevelopmentMode(pageReference);
		Schema.SObjectType sObjectType;
		try {
			sObjectType = Id.valueOf(recordId).getSobjectType();
		} catch (Exception e) {
			// catch Invalid Id
		}
		if (sObjectType != null) {
			String logId;
			if (sObjectType == ISSUE_SOBJECT_TYPE) {
				List<Issue__c> issues = [SELECT Id, Log__c FROM Issue__c WHERE Id = :recordId];
				if (!issues.isEmpty()) logId = issues[0].Log__c;
			} else if (sObjectType == LOG_SOBJECT_TYPE) {
				logId = recordId;
			}
			if (String.isNotBlank(logId)) {
				this.log = [
						SELECT Id, Name, Flow_Link__c, Stacktrace__c, Stacktrace_Parse_Result__c, Stack_trace_parse_result_available__c, Is_Parent__c, Type__c, Summary__c, Organization_Url__c, Category__c, Async_Job_Id__c, Issue__c,
						(SELECT Id, ContentDocument.LatestPublishedVersion.Id, ContentDocument.LatestPublishedVersion.PathOnClient FROM ContentDocumentLinks)
						FROM Log__c
						WHERE Id = :logId
				];

				if (log.Is_Parent__c) {
					List<Log__c> childLogs = [
							SELECT Id, Name, Summary__c, Category__c, Type__c, Stacktrace__c, Organization_Url__c, Created_Timestamp__c, Stacktrace_Parse_Result__c, Stack_trace_parse_result_available__c, Async_Job_Id__c, Flow_Link__c
							FROM Log__c
							WHERE Parent__c = :log.Id
							AND Summary__c LIKE 'Log After:%'
							ORDER BY Created_Timestamp__c DESC
							LIMIT 1
					];
					if(!childLogs.isEmpty()) {
						this.log = childLogs[0];
					}
				}

				for(ContentDocumentLink cdl : log?.ContentDocumentLinks) {
					if(cdl?.ContentDocument?.LatestPublishedVersion?.PathOnClient == ErrorEmailHandler.STACK_TRACE_CV_NAME) {
						this.stacktraceCvId = cdl.ContentDocument.LatestPublishedVersion.Id;
					}
					if(cdl?.ContentDocument?.LatestPublishedVersion?.PathOnClient == ErrorEmailHandler.STACK_TRACE_PARSE_RESULT_CV_NAME) {
						this.stacktraceParseResultCvId = cdl.ContentDocument.LatestPublishedVersion.Id;
					}
				}

				isBlurMode = !BlurModeService.isAvailableDebugView(this.log.Id);
				if (isBlurMode) {
					blurModeUrlParameter = BlurModeService.getEncryptedUrlParameter();
				}
			}
		}
	}

	@RemoteAction
	global static String remoteActionHandler(String input) {
		String result;
		String methodName;
		String method;
		RemoteActionResponse response = new RemoteActionResponse();
		try {
			Map<String, Object> request = (Map<String, Object> )JSON.deserializeUntyped(input);
			response.params = request;
			method = (String)request.get('method');
			methodName = method;
			Object data = request.get('data');
			if (method == 'getContentDocumentIds') {
				response.data = getContentDocumentIds(data);
			} else if (method == 'getSummaryContentDocumentId') {
				response.data = getSummaryContentDocumentId(data);
			} else if (method == 'getAppPermissions') {
				response.data = AdminService.getAppPermissions(data);
			} else if (method == 'replayCallout') {
				response.data = replayCallout(data);
			} else {
				response.error = 'Action not found';
			}
			result = JSON.serialize(response);
		}
		catch (Exception e) {
			response.error = e.getMessage();
			response.stack = e.getStackTraceString();
			if(method != 'replayCallout') {
				Logger.getInstance().internalError(e, StacktraceViewerController.class.getName(), 'remoteActionHandler' + (String.isNotBlank(methodName) ? '.' + methodName : ''));
			}
		}
		finally {
			try {
				result = JSON.serialize(response);
			}
			catch (Exception e) {
				if (method != 'replayCallout') {
					Logger.getInstance().internalError(e, StacktraceViewerController.class.getName(), 'remoteActionHandler.serializeResponse');
				}
			}
		}
		return result;
	}

	private static Set<String> getContentDocumentIds(Object data) {
		Map<String, Object> payload = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(data));
		String logId = (String)payload.get('logId');
		return new Map<String, AggregateResult>([SELECT ContentDocument.LatestPublishedVersionId Id FROM ContentDocumentLink WHERE LinkedEntityId = :logId AND (NOT ContentDocument.Title LIKE '%summary%') GROUP BY ContentDocument.LatestPublishedVersionId]).keySet();
	}

	private static Set<String> getSummaryContentDocumentId(Object data) {
		Map<String, Object> payload = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(data));
		String logId = (String)payload.get('logId');
		return new Map<String, AggregateResult>([SELECT ContentDocument.LatestPublishedVersionId Id FROM ContentDocumentLink WHERE LinkedEntityId = :logId AND ContentDocument.Title LIKE '%summary%' GROUP BY ContentDocument.LatestPublishedVersionId]).keySet();
	}

	private static Map<String, Object> replayCallout(Object data) {
		Map<String, Object> payload = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(data));
		String endpoint = (String)payload.get('endpoint');
		String method = (String)payload.get('method');
		Map<String, String> headers = new Map<String, String>();
		if (payload.get('headers') != null) {
			Map<String, Object> mapHeaders = (Map<String, Object>)payload.get('headers');
			for (String key : mapHeaders.keySet()) {
				headers.put(key, String.valueOf(mapHeaders.get(key)));
			}
		}
		String body = (String)payload.get('body');
		HttpResponse res = HttpUtils.send(endpoint, method, headers, body);
		return new HttpResponseWrapper(res).formatResponse();
	}

	public class RemoteActionResponse {
		public Object params;
		public Object data;
		public String error;
		public String stack;
	}
}