main/default/objects/AI_Event__e/AI_Event__e.object-meta.xml
<CustomObject>
    <label>AI Event</label>
    <pluralLabel>AI Event</pluralLabel>
</CustomObject>

main/default/objects/AI_Event__e/fields/Analysis__c.field-meta.xml
<CustomField>
    <fullName>Analysis__c</fullName>
    <label>Analysis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/AI_Event__e/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Connected_Org__c/Connected_Org__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Connected Org</label>
</CustomObject>

main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>ISS-{00000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Issue__c/fields/Analysis__c.field-meta.xml
<CustomField>
    <fullName>Analysis__c</fullName>
    <label>Analysis</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Issue__c/fields/Analysis_Statuses_Details__c.field-meta.xml
<CustomField>
    <fullName>Analysis_Statuses_Details__c</fullName>
    <label>Analysis Statuses Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Issue__c/fields/Average_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Average_Frequency__c</fullName>
    <label>Average Frequency (days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Issue__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Log__r.Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

main/default/objects/Issue__c/fields/First_Occurred_On__c.field-meta.xml
<CustomField>
    <fullName>First_Occurred_On__c</fullName>
    <label>First Occurred On</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Issue__c/fields/Functional_Area__c.field-meta.xml
<CustomField>
    <fullName>Functional_Area__c</fullName>
    <formula>TEXT(Log__r.Area__c)</formula>
    <label>Functional Area</label>
    <type>Text</type>
</CustomField>

main/default/objects/Issue__c/fields/Impacted_Objects_Count__c.field-meta.xml
<CustomField>
    <fullName>Impacted_Objects_Count__c</fullName>
    <label>Impacted Objects Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Issue__c/fields/Impacted_Users_Count__c.field-meta.xml
<CustomField>
    <fullName>Impacted_Users_Count__c</fullName>
    <label>Impacted Users Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Issue__c/fields/Issue_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Issue_Analysis__c</fullName>
    <label>Issue Analysis</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Issue__c/fields/Last_Occurred_On__c.field-meta.xml
<CustomField>
    <fullName>Last_Occurred_On__c</fullName>
    <label>Last Occurred On</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Issue__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Issue__c/fields/Organization_Name__c.field-meta.xml
<CustomField>
    <fullName>Organization_Name__c</fullName>
    <label>Organization Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Triaged</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Issue__c/recordTypes/Issue.recordType-meta.xml
<RecordType>
    <fullName>Issue</fullName>
    <active>true</active>
    <label>Issue</label>
</RecordType>

main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Log__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Email-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Case</fullName>
            </value>
            <value>
                <fullName>Web-to-Lead</fullName>
            </value>
            <value>
                <fullName>Pharos Error</fullName>
            </value>
            <value>
                <fullName>Mulesoft</fullName>
            </value>
            <value>
                <fullName>OmniStudio</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/First_Occurred_On__c.field-meta.xml
<CustomField>
    <fullName>First_Occurred_On__c</fullName>
    <label>First Occurred On</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Log__c/fields/Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_API_Name__c</fullName>
    <label>Flow API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Flow_Version__c.field-meta.xml
<CustomField>
    <fullName>Flow_Version__c</fullName>
    <label>Flow Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Issue</label>
    <referenceTo>Issue__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Log__c/fields/Organization_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Id__c</fullName>
    <label>Organization Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Organization_Url__c.field-meta.xml
<CustomField>
    <fullName>Organization_Url__c</fullName>
    <label>Organization Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Post_Processing_Settings__c.field-meta.xml
<CustomField>
    <fullName>Post_Processing_Settings__c</fullName>
    <label>Post Processing Settings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Log__c/fields/Related_Objects__c.field-meta.xml
<CustomField>
    <fullName>Related_Objects__c</fullName>
    <label>Related Objects</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Setup_Audit_Trail__c.field-meta.xml
<CustomField>
    <fullName>Setup_Audit_Trail__c</fullName>
    <label>Setup Audit Trail</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <label>Stacktrace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/fields/Stacktrace_Parse_Result__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace_Parse_Result__c</fullName>
    <label>Stacktrace Parse Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Log__c/recordTypes/Debug.recordType-meta.xml
<RecordType>
    <fullName>Debug</fullName>
    <active>true</active>
    <label>Debug</label>
</RecordType>

main/default/objects/Log__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <label>Error</label>
</RecordType>

main/default/objects/Log__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/classes/AIAnalysis.cls
public with sharing class AIAnalysis {

	public List<AI_Event__e> events = new List<AI_Event__e>();
	public Map<String, Issue__c> issues = new Map<String, Issue__c>();
	public Map<String, AIAnalysisService> analysisServiceByIssueId = new Map<String, AIAnalysisService>();

	private String errorMessage;

	public static AIAnalysis getInstance(Object input) {
		System.debug('++++AIAnalysis.getInstance input: ' + JSON.serialize(input));
		System.debug('++++AIAnalysis instance already exists: ' + (instance != null));
		
		if (instance != null) {
			System.debug('++++AIAnalysis returning existing instance with issues: ' + instance.issues.keySet());
			System.debug('++++AIAnalysis existing instance events count: ' + (instance.events != null ? instance.events.size() : 0));
		}
		
		if (instance == null) {
			System.debug('++++AIAnalysis creating new instance');
			if (input instanceof Set<Id> || input instanceof Set<String>) {
				instance = new AIAnalysis((Set<String>)input);
			} else if (input instanceof List<AI_Event__e>) {
				instance = new AIAnalysis((List<AI_Event__e>)input);
			} else {
				throw new AIAnalysisException('Unsupported input type: ' + JSON.serialize(input));
			}
			System.debug('++++AIAnalysis new instance created with issues: ' + instance.issues.keySet());
		}
		return instance;
	}

	private static AIAnalysis instance = null;

	private AIAnalysis(Set<String> issueIds) {
		this.issues = getIssues(issueIds);
	}

	private AIAnalysis(List<AI_Event__e> events) {
		System.debug('++++AIAnalysis constructor called with events: ' + events.size());
		this.events = events;
		Set<String> issueIds = new Set<String>();
		for (AI_Event__e event : events) {
			System.debug('++++AIAnalysis processing event - Record_Id__c: ' + event.Record_Id__c + ', Analysis__c: ' + event.Analysis__c + ', Status__c: ' + event.Status__c);
			issueIds.add(event.Record_Id__c);
		}
		System.debug('++++AIAnalysis extracted issue IDs: ' + issueIds);
		this.issues = getIssues(issueIds);
		System.debug('++++AIAnalysis loaded issues: ' + this.issues.keySet());
	}

	public void init() {
		System.debug('++++AIAnalysis.init called');
		System.debug('++++AIAnalysis.init issues count: ' + issues.size());
		System.debug('++++AIAnalysis.init events count: ' + (events != null ? events.size() : 0));
		
		errorMessage = checkAnalysisPermission();
		System.debug('++++AIAnalysis.init permission check result: ' + errorMessage);
		
		if (String.isBlank(errorMessage)) {
			System.debug('++++AIAnalysis.init creating analysis services for issues: ' + issues.keySet());
			for (Issue__c issue : this.issues.values()) {
				this.analysisServiceByIssueId.put(issue.Id, new AIAnalysisService(issue));
			}
			System.debug('++++AIAnalysis.init created analysis services for: ' + analysisServiceByIssueId.keySet());
			
			if (events != null && !events.isEmpty()) {
				System.debug('++++AIAnalysis.init calling setContentDocumentId and setResult');
				setContentDocumentId();
				setResult();
			} else {
				System.debug('++++AIAnalysis.init no events to process');
			}
		} else {
			System.debug('++++AIAnalysis.init calling internalError due to permission issue');
			internalError();
		}
	}

	public void inProgress() {
		if (String.isNotBlank(errorMessage)) return;
		for (AIAnalysisService analysisService : analysisServiceByIssueId.values()) {
			analysisService.inProgress();
		}
	}

	public void analysis() {
		if (String.isNotBlank(errorMessage)) return;
		for (AIAnalysisService analysisService : analysisServiceByIssueId.values()) {
			analysisService.analysis();
		}
	}

	public void createContentVersions() {
		if (String.isNotBlank(errorMessage)) return;
		List<ContentVersion> contentVersions = new List<ContentVersion>();
		for (Issue__c issue : issues.values()) {
			for (String analysis : AIAnalysisService.ANALYSIS_MAP.keySet()) {
				ContentVersion contentVersion = analysisServiceByIssueId.get(issue.Id).createContentVersion(analysis);
				if (contentVersion != null) contentVersions.add(contentVersion);
			}
		}
		DatabaseUtils.getInstance().performUpsertDML(contentVersions, Schema.SObjectType.ContentVersion)
				.handleError(AIAnalysis.class.getName(), '.createContentVersions', Logger.getInstance());
		contentVersions = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id IN :contentVersions AND IsLatest = TRUE];
		List<ContentDocumentLink> existContentDocumentLinks = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN :issues.keySet()];
		List<ContentDocumentLink> contentDocumentLinks = new List<ContentDocumentLink>();
		for (Issue__c issue : issues.values()) {
			for (String analysis : AIAnalysisService.ANALYSIS_MAP.keySet()) {
				String title = getTitleString(issue.Name, analysis);
				for (ContentVersion contentVersion : contentVersions) {
					if (title == contentVersion.Title) {
						Boolean isExist = false;
						for (ContentDocumentLink contentDocumentLink : existContentDocumentLinks) {
							if (contentDocumentLink.ContentDocumentId == contentVersion.ContentDocumentId) {
								isExist = true;
								break;
							}
						}
						if (!isExist) {
							ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
							contentDocumentLink.ContentDocumentId = contentVersion.ContentDocumentId;
							contentDocumentLink.LinkedEntityId = issue.Id;
							contentDocumentLink.ShareType = 'I';
							contentDocumentLinks.add(contentDocumentLink);
						}
					}
				}
			}
		}
		DatabaseUtils.getInstance().performInsertDML(contentDocumentLinks, Schema.SObjectType.ContentDocumentLink)
				.handleError(AIAnalysis.class.getName(), '.createContentVersions', Logger.getInstance());
	}

	public void flush() {
		if (String.isNotBlank(errorMessage)) return;
		for (AIAnalysisService analysisService : analysisServiceByIssueId.values()) {
			analysisService.issueStatus();
		}
		DatabaseUtils.getInstance().performUpdateDML(issues.values(), Schema.SObjectType.Issue__c)
				.handleError(AIAnalysis.class.getName(), '.flush', Logger.getInstance());
		Logger.getInstance().flush();
	}

	public static String checkAnalysisPermission() {
		String result;
		if (!PermissionsUtil.IssueAnalysisEnabled) {
			result = AIAnalysisService.ISSUE_ANALYSIS_DISABLED_MESSAGE;
		} else if (!ConfigUtil.OPEN_AI_SETTINGS.OpenAI_Enabled__c || String.isBlank(ConfigUtil.OPEN_AI_SETTINGS.Token__c)) {
			result = AIAnalysisService.CONFIGURE_OPEN_AI_SETTINGS_MESSAGE;
		}
		return result;
	}

	private static Map<String, Issue__c> getIssues(Set<String> issueIds) {
		return new Map<String, Issue__c>([
				SELECT
						Id,
						Name,
						Category__c,
						Functional_Area__c,
						First_Occurred_On__c,
						Last_Occurred_On__c,
						Impacted_Objects_Count__c,
						Impacted_Users_Count__c,
						Average_Frequency__c,
						Issue_Analysis__c,
						Analysis_Statuses_Details__c,
						Log__c,
						Log__r.Type__c,
						Log__r.Category__c,
						Log__r.Details__c,
						Log__r.Organization_Id__c,
						Log__r.Related_Objects__c,
						Log__r.Flow_API_Name__c,
						Log__r.Flow_Version__c,
						Log__r.Stacktrace_Parse_Result__c,
						Log__r.Stacktrace__c,
						Log__r.Setup_Audit_Trail__c
				FROM Issue__c
				WHERE Id IN :issueIds]);
	}

	private void setContentDocumentId() {
		Map<String, String> contentDocumentIdsByTitle = getContentDocumentIdsByTitle();
		for (Issue__c issue : this.issues.values()) {
			for (String analysis : AIAnalysisService.ANALYSIS_MAP.keySet()) {
				String title = getTitleString(issue.Name, analysis);
				if (contentDocumentIdsByTitle.containsKey(title)) {
					analysisServiceByIssueId.get(issue.Id).setContentDocumentId(analysis, contentDocumentIdsByTitle.get(title));
				}
			}
		}
	}

	private void setResult() {
		System.debug('++++AIAnalysis.setResult called with events count: ' + events.size());
		System.debug('++++AIAnalysis.setResult available analysis services for issues: ' + analysisServiceByIssueId.keySet());
		
		for (AI_Event__e event : events) {
			System.debug('++++AIAnalysis.setResult processing event - Record_Id__c: ' + event.Record_Id__c + ', Analysis__c: ' + event.Analysis__c + ', Status__c: ' + event.Status__c);
			System.debug('++++AIAnalysis.setResult checking if issue exists in analysis services: ' + analysisServiceByIssueId.containsKey(event.Record_Id__c));
			
			if (analysisServiceByIssueId.containsKey(event.Record_Id__c)) {
				try {
					analysisServiceByIssueId.get(event.Record_Id__c).setResult(event.Analysis__c, event.Status__c, event.Result__c);
					System.debug('++++AIAnalysis.setResult successfully set result for event');
				} catch (Exception e) {
					System.debug('++++AIAnalysis.setResult error setting result: ' + e.getMessage());
					System.debug('++++AIAnalysis.setResult error stack trace: ' + e.getStackTraceString());
				}
			} else {
				System.debug('++++AIAnalysis.setResult ERROR: Issue ' + event.Record_Id__c + ' not found in analysis services!');
				System.debug('++++AIAnalysis.setResult available issues: ' + analysisServiceByIssueId.keySet());
			}
		}
	}

	private Map<String, String> getContentDocumentIdsByTitle() {
		Map<String, String> contentDocumentIdsByTitle = new Map<String, String>();
		List<ContentDocumentLink> contentDocumentLinks = [
				SELECT Id, LinkedEntityId, ContentDocumentId, ContentDocument.Title
				FROM ContentDocumentLink
				WHERE LinkedEntityId IN :issues.keySet()
		];
		for (ContentDocumentLink contentDocumentLink : contentDocumentLinks) {
			contentDocumentIdsByTitle.put(contentDocumentLink.ContentDocument.Title, contentDocumentLink.ContentDocumentId);
		}
		return contentDocumentIdsByTitle;
	}

	public void setVersionData() {
		Set<String> titles = new Set<String>();
		for (Issue__c issue : issues.values()) {
			for (String analysis : AIAnalysisService.ANALYSIS_MAP.keySet()) {
				titles.add(getTitleString(issue.Name, analysis));
			}
		}
		List<ContentDocumentLink> contentDocumentLinks = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN :issues.keySet()];
		Set<String> contentDocumentIds = new Set<String>();
		for (ContentDocumentLink contentDocumentLink : contentDocumentLinks) {
			contentDocumentIds.add(contentDocumentLink.ContentDocumentId);
		}
		List<ContentVersion> contentVersions = [SELECT Id, Title, VersionData FROM ContentVersion WHERE ContentDocumentId IN :contentDocumentIds AND Title IN :titles AND IsLatest = TRUE];
		for (Issue__c issue : issues.values()) {
			for (ContentVersion contentVersion : contentVersions) {
				if (contentVersion.Title.contains(issue.Name)) {
					analysisServiceByIssueId.get(issue.Id).setVersionData(contentVersion.Title.removeStart(issue.Name + '_'), contentVersion.VersionData.toString());
				}
			}
		}
	}

	public String getFormattedData(String issueId, String context) {
		String convertedData = '';
		for (String analysis : AIAnalysisService.ANALYSIS_MAP.keySet()) {
			String formattedData = getFormattedData(issueId, analysis, context);
			if (formattedData != null) {
				convertedData += formattedData;
			}
		}
		return convertedData;
	}

	public String getFormattedData(String issueId, String analysis, String context) {
		return analysisServiceByIssueId.get(issueId).getFormattedData(analysis, context);
	}

	public static String getTitleString(String issueName, String analysis) {
		return issueName + '_' + analysis;
	}

	public void internalError() {
		Connected_Org__c corg = ConnectedOrgService.getConnectedOrgById(UserInfo.getOrganizationId());
		Logger.getInstance().add(LogBuilder.getInstance()
				.category(Logger.CATEGORY_PHAROS_ERROR)
				.summary(errorMessage)
				.details(errorMessage + '\n' + JSON.serialize(issues.keySet()))
				.area(Logger.AREA_PHAROS_ERROR)
				.type('Issue Analysis')
				.attribute(Schema.SObjectType.Log__c.fields.Organization_Id__c.name, corg?.Name)
				.attribute(Schema.SObjectType.Log__c.fields.Organization_Name__c.name, corg?.Title__c)
				.attribute(Schema.SObjectType.Log__c.fields.Organization_Url__c.name, corg?.Instance_Url__c)
				.attribute(Schema.SObjectType.Log__c.fields.Related_Objects__c.name, JSON.serialize(issues.keySet()))
				.attribute(Schema.SObjectType.Log__c.fields.Post_Processing_Settings__c.name, '["RO"]')
				.createIssue()
				.build());
	}

	public class AIAnalysisException extends Exception {}

}